import Foundation

struct L10n {
    static func text(_ key: String, _ language: AppSettingsStore.Language) -> String {
        let code = language.rawValue
        return dictionary[code]?[key] ?? dictionary["en"]?[key] ?? key
    }

    static func format(_ key: String, _ language: AppSettingsStore.Language, _ arguments: CVarArg...) -> String {
        String(
            format: text(key, language),
            locale: Locale(identifier: language.localeIdentifier),
            arguments: arguments
        )
    }

    static func city(_ raw: String, _ language: AppSettingsStore.Language) -> String {
        switch raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
        case "makkah", "mecca": return text("city_makkah", language)
        case "madinah", "medina": return text("city_madinah", language)
        default: return raw
        }
    }

    static func date(_ raw: String, _ language: AppSettingsStore.Language) -> String {
        let input = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !input.isEmpty else { return raw }

        let source = DateFormatter()
        source.locale = Locale(identifier: "en_US_POSIX")
        source.calendar = Calendar(identifier: .gregorian)
        source.timeZone = TimeZone(secondsFromGMT: 0)
        source.dateFormat = "yyyy-MM-dd"
        guard let parsed = source.date(from: String(input.prefix(10))) else { return raw }

        let output = DateFormatter()
        output.locale = Locale(identifier: language.localeIdentifier)
        output.calendar = Calendar(identifier: .gregorian)
        output.timeZone = TimeZone(secondsFromGMT: 0)
        output.dateStyle = .medium
        output.timeStyle = .none
        return output.string(from: parsed)
    }

    static func status(_ raw: String, _ language: AppSettingsStore.Language) -> String {
        let normalized = raw.uppercased()
        switch normalized {
        case "AVAILABILITY_CHECK": return text("status_availability", language)
        case "PAYMENT_PENDING": return text("status_payment", language)
        case "BOOKING_CONFIRMED": return text("status_confirmed", language)
        case "READY_TO_TRAVEL": return text("status_ready", language)
        case "COMPLETED": return text("status_completed", language)
        default: return raw.replacingOccurrences(of: "_", with: " ").capitalized
        }
    }

    static func error(_ error: Error, _ language: AppSettingsStore.Language) -> String {
        if let flightError = error as? FlightEngineAvailabilityError {
            switch flightError {
            case .packageEngineUnavailable:
                return text("flight_error_service", language)
            case .makkahPricingMissing:
                return text("flight_error_makkah", language)
            case .madinahPricingMissing:
                return text("flight_error_madinah", language)
            case .realOutboundRequired:
                return text("flight_error_outbound", language)
            }
        }
        if let pricingError = error as? FlightPricingBridgeError {
            switch pricingError {
            case .unresolvedFareScope(let provider):
                return format("flight_error_fare_scope", language, provider)
            case .candidateMissing(let id):
                return format("flight_error_candidate", language, id)
            case .insufficientQuotedOptions(let found, let minimum):
                return format("flight_error_minimum", language, found, minimum)
            }
        }
        if let orchestratorError = error as? FlightBotOrchestrator.OrchestratorError {
            switch orchestratorError {
            case .insufficientResults(let found, let minimum, let blockedProviders):
                if blockedProviders.isEmpty {
                    return format("flight_error_insufficient", language, found, minimum)
                }
                return format(
                    "flight_error_insufficient_challenge",
                    language,
                    found,
                    minimum,
                    blockedProviders.joined(separator: ", ")
                )
            }
        }
        if let botError = error as? FlightBotRunner.BotError {
            switch botError {
            case .invalidPage:
                return text("flight_bot_invalid_page", language)
            case .challengeRequired(let challenge):
                return format("flight_bot_challenge", language, challenge.providerName)
            case .noCandidates:
                return text("flight_bot_no_candidates", language)
            case .timeout:
                return text("flight_bot_timeout", language)
            }
        }
        if let urlError = error as? URLError {
            switch urlError.code {
            case .notConnectedToInternet, .networkConnectionLost:
                return text("error_offline", language)
            case .timedOut:
                return text("error_timeout", language)
            default:
                return text("error_network", language)
            }
        }
        guard let apiError = error as? APIError else { return text("error_unknown", language) }
        switch apiError {
        case .invalidResponse:
            return text("error_invalid_response", language)
        case .status(let code):
            return format("error_status", language, code)
        case .server(_, let message):
            let normalized = message.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
            let localized: String
            switch normalized {
            case "CHAT_NOT_FOUND", "BOOKING_NOT_FOUND":
                localized = text("error_booking_access", language)
            case "RATE_LIMIT":
                localized = text("error_rate_limit", language)
            case "CHAT_READ_FAILED":
                localized = text("error_chat_load", language)
            case "CHAT_SEND_FAILED":
                localized = text("error_chat_send", language)
            case "CHAT_DB_NOT_CONFIGURED", "BOOKING_DB_NOT_CONFIGURED":
                localized = text("error_service_unavailable", language)
            case "INVALID_REQUEST", "EMPTY_MESSAGE", "INVALID_BOOKING":
                localized = text("error_invalid_request", language)
            default:
                localized = format("error_server_named", language, message)
            }
            return normalized.isEmpty ? localized : "\(localized) [\(normalized)]"
        case .decoding:
            return text("error_decoding", language)
        case .missingBookingToken:
            return text("error_missing_booking_token", language)
        }
    }

    private static let dictionary: [String: [String: String]] = [
        "en": [
            "tab_home": "Home",
            "tab_hotels": "Hotels",
            "tab_booking": "Booking",
            "tab_care": "Care",
            "tab_umrah": "Umrah",
            "profile_placeholder": "Your profile",
            "profile_subtitle_empty": "Add your name and contacts",
            "profile_subtitle_ready": "Pilgrim profile",
            "settings_title": "Settings",
            "settings_done": "Done",
            "profile_section": "Profile",
            "language_section": "Language",
            "appearance_section": "Appearance",
            "field_first_name": "First name",
            "field_last_name": "Last name",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "App language",
            "theme_label": "Theme",
            "appearance_system": "Match iPhone",
            "appearance_light": "Light",
            "appearance_dark": "Dark",
            "language_russian": "Russian",
            "language_english": "English",
            "language_uzbek": "Uzbek",
            "language_uzbek_cyr": "Uzbek (Cyrillic)",
            "home_hero_kicker": "YOUR UMRAH",
            "home_hero_title": "Your Umrah.\nYour path.",
            "home_hero_body": "Flights, stay and support — organized around your trip, not around a large group.",
            "home_hero_cta": "Build my Umrah",
            "home_hero_badge": "Final price is shown before booking",
            "hotels_title": "iumrah Hotel Space",
            "hotels_subtitle": "Hotels selected by the iumrah team for pilgrims who want reliable service, a convenient location and a calmer stay.",
            "hotels_note": "iumrah does not own these hotels. We carefully select and monitor properties that suit our pilgrims.",
            "hotels_makkah": "Makkah selection",
            "city_makkah": "Makkah",
            "city_madinah": "Madinah",
            "flight_airline_unknown": "Airline",
            "hotels_madinah": "Madinah selection",
            "hotels_selected_badge": "Selected by iumrah",
            "hotels_load_error": "Could not load hotels right now.",
            "booking_hero_kicker": "NEW TRIP",
            "booking_hero_title": "Build your Umrah",
            "booking_hero_body": "Choose dates, travelers and a travel tier. iumrah will then suggest a hotel and find matching flights with a clear package price.",
            "booking_hero_cta": "Create my Umrah",
            "booking_empty_title": "No bookings yet",
            "booking_empty_body": "After confirmation, your first trip will appear here.",
            "trip_intro_kicker": "BUILD YOUR UMRAH",
            "trip_intro_title": "Let's start with your trip",
            "trip_intro_body": "Choose route, dates and travelers. iumrah uses these details to suggest a hotel and find suitable flights.",
            "step_trip": "Trip",
            "step_hotel": "Hotel",
            "step_flight": "Flight",
            "step_ready": "Ready",
            "trip_continue_hotel": "Continue to hotel",
            "checkout_title": "Let's verify your trip",
            "checkout_subtitle": "Before confirmation, iumrah checks availability for your selected hotel and flights one more time.",
            "next_title": "What happens next",
            "next_one": "Your trip gets a protected booking ID",
            "next_two": "Availability checking starts",
            "next_three": "Status appears in Booking",
            "next_four": "iumrah Care chat links to this trip",
            "checkout_cta": "Review and create booking",
            "success_title": "Trip created",
            "success_body": "iumrah is now checking availability. Your status and support chat are already linked to this trip.",
            "open_booking": "Open booking",
            "open_care": "Open iumrah Care",
            "profile_required_title": "Pilgrim details",
            "profile_required_body": "Before booking, please add your first name, last name and at least one contact so support can recognize the pilgrim.",
            "save_continue": "Save and continue",
            "care_title": "iumrah Care",
            "care_subtitle": "Support stays with your trip before, during and after Umrah.",
            "care_chats": "Your chats",
            "care_chats_subtitle": "Each chat is linked to a specific trip, so there is no need to explain the route, dates and hotel again.",
            "care_locked_title": "Chat opens after booking",
            "care_locked_body": "Build your trip and send it for availability checking. After that, support will be linked to your booking.",
            "care_promise_title": "Independent does not mean alone.",
            "care_promise_body": "Before the trip, on the road and during Umrah, iumrah Care remains one support line linked to your trip.",
            "chat_online": "online",
            "chat_unavailable": "Chat unavailable",
            "chat_empty_title": "Start the conversation",
            "chat_empty_body": "Ask about your booking, flight, hotel, transfer or route.",
            "chat_placeholder": "Message…",
            "chat_load": "Loading chat…",
            "chat_retry": "Retry",
            "chat_you": "You",
            "chat_staff": "iumrah Care",
            "status_availability": "Checking availability",
            "status_payment": "Awaiting payment",
            "status_confirmed": "Booking confirmed",
            "status_ready": "Ready to travel",
            "status_completed": "Trip completed",
            "detail_booking": "Booking",
            "detail_updates": "Status updates automatically",
            "detail_chat_cta": "Chat with iumrah Care",
            "detail_not_found": "Booking not found",
            "detail_dates": "Travel dates",
            "detail_hotel": "Hotel",
            "route_label": "Route",
            "route_return": "Return",
            "total_for": "Total for",
            "travelers": "travelers",
            "back": "Back",
            "profile_accessibility": "Profile",
            "trip_origin_title": "Where your trip starts",
            "trip_destination_title": "Where do you want to go",
            "trip_route_picker": "Route",
            "trip_arrival_title": "Which airport first",
            "trip_arrival_picker": "Arrival airport",
            "trip_arrival_madinah_hint": "Start with Madinah. Return flights will be searched from Jeddah.",
            "trip_arrival_jeddah_hint": "Start with Makkah via Jeddah. Return flights will be searched from Madinah.",
            "trip_dates_title": "When do you want to travel",
            "departure": "Departure",
            "return": "Return",
            "trip_flexible_hint": "Flexible dates help find more suitable flights.",
            "trip_travelers_title": "Who travels with you",
            "trip_travelers_body": "Rooming and flights will be calculated for your family or group.",
            "adults": "Adults",
            "children": "Children",
            "children_age": "2–11 years",
            "infants": "Infants",
            "infants_age": "under 2",
            "rooms": "Rooms",
            "hotel_level": "Hotel level",
            "trip_format_title": "What trip format fits you",
            "popular": "POPULAR",
            "tier_economy": "Economy",
            "tier_economy_subtitle": "Essentials for a calm Umrah.",
            "tier_standard": "Standard",
            "tier_standard_subtitle": "Balance of location, comfort and value.",
            "tier_comfort": "Comfort",
            "tier_comfort_subtitle": "More comfort every day.",
            "tier_luxury": "Luxury",
            "tier_luxury_subtitle": "Umrah without compromises.",
            "flex_exact": "Exact",
            "flex_pm1": "±1 day",
            "flex_pm2": "±2 days",
            "flex_weekend": "Weekend",
            "scope_makkah": "Makkah only",
            "scope_both": "Makkah + Madinah",
            "airport_jeddah": "Jeddah",
            "airport_madinah": "Madinah",
            "airport_jeddah_full": "Jeddah · for Makkah",
            "airport_search_title": "Find your departure airport",
            "airport_search_body": "Search by city, airport name or three-letter code — for example TAS, Tashkent, Istanbul.",
            "airport_none": "Nothing found",
            "airport_none_body": "Try another city or airport code.",
            "airport_search_failed": "Could not search airports right now.",
            "airport_title": "Departure airport",
            "close": "Close",
            "primary_hotel_title": "We selected a hotel for your trip",
            "primary_hotel_badge": "Recommended by iumrah",
            "primary_hotel_subtitle": "It fits your %@ level and %d★ hotel preference. Keep it or browse other curated options.",
            "primary_hotel_loading": "Loading the iumrah hotel catalog…",
            "retry": "Retry",
            "primary_hotel_continue": "Continue with this hotel",
            "primary_hotel_other": "See other options",
            "primary_hotel_empty": "No matching hotel is available in the curated catalog yet.",
            "hotel_change_title": "Choose another hotel",
            "hotel_catalog_eyebrow": "iumrah catalog",
            "hotel_change_body": "Only hotels selected by iumrah for pilgrims are shown here.",
            "selected": "Selected",
            "flight_search_hero": "Best flights are almost ready",
            "flight_search_airlines": "Checking airlines",
            "flight_search_dates": "Comparing suitable dates",
            "flight_search_reprice": "Recalculating the whole trip",
            "flight_search_almost": "Best flights are almost ready",
            "flight_ready_title": "Ready",
            "flight_ready_body": "Suitable options were found and the trip price was recalculated.",
            "flight_out_title": "Choose your outbound flight",
            "flight_out_eyebrow": "Outbound",
            "flight_out_body": "Each price shows the final cost of your entire Umrah with that flight option.",
            "flight_choose_return": "Choose return flight",
            "flight_return_title": "Choose your return flight",
            "flight_return_eyebrow": "Return",
            "flight_return_body": "The price includes your selected outbound flight and represents the complete package.",
            "flight_view_package": "View my completed Umrah",
            "flight_select_outbound_first": "Choose an outbound flight first.",
            "flight_nav_out": "Flight",
            "flight_nav_return": "Return",
            "flight_recommended": "Recommended",
            "flight_whole_package": "Whole package",
            "flight_package_contents": "Hotel + flights + services",
            "flight_direct": "Direct",
            "flight_details_cta": "Flight details",
            "flight_details_title": "Flight details",
            "flight_details_route": "%@ → %@",
            "flight_segment_count": "Flight %d of %d",
            "flight_detail_duration": "Flight time",
            "flight_detail_aircraft": "Aircraft",
            "flight_detail_cabin": "Cabin",
            "flight_detail_operated_by": "Operated by",
            "flight_detail_unknown": "Not provided",
            "flight_terminal": "Terminal %@",
            "flight_layover_title": "Layover in %@",
            "flight_layover_airport_change": "Airport change in %@",
            "flight_layover_overnight": "Overnight layover",
            "flight_layover_summary": "%@ · %@ layover",
            "flight_airport_change": "%@ · airport change · %@",
            "flight_duration_short": "%dh %dm",
            "flight_hours_short": "%dh",
            "flight_minutes_short": "%dm",
            "flight_cabin_economy": "Economy",
            "flight_cabin_business": "Business",
            "flight_cabin_premium": "Premium economy",
            "flight_cabin_first": "First",
            "flight_details_price_note": "This is the final Umrah package price per person with this flight. The ticket price is not shown separately.",
            "flight_stops": "%d stops",
            "challenge_open": "Complete verification",
            "flight_retry": "Retry search",
            "final_nav_title": "Your trip",
            "final_calculating": "Calculating final price…",
            "final_title": "Your Umrah is ready",
            "final_body": "We built the trip around your dates and preferences. Flights, hotel and selected services are connected in one package.",
            "final_price": "Final price",
            "final_total_group": "Total for %d travelers: %@",
            "final_price_note": "This is the price of the complete selected package",
            "final_in_trip": "In your trip",
            "final_outbound": "Outbound flight",
            "final_hotel": "Hotel",
            "final_transfer": "Transfers and services",
            "final_return": "Return flight",
            "final_care": "iumrah Care",
            "final_visa": "Visa",
            "included": "Included",
            "final_before": "Before booking",
            "final_check_one": "We will check availability once more",
            "final_check_two": "Conditions remain visible before confirmation",
            "final_check_three": "After booking, the trip appears in Booking and iumrah Care",
            "final_book_cta": "Book my Umrah",
            "notifications_title": "Trip notifications",
            "notifications_enable": "Enable notifications",
            "notifications_enabled": "Notifications enabled",
            "notifications_not_determined": "Notifications are not enabled yet",
            "notifications_denied": "Notifications are disabled in iPhone Settings",
            "notifications_registering": "Allowed · registering this device",
            "notifications_provisional": "Quiet notifications are enabled",
            "notifications_ephemeral": "Temporary permission is active",
            "notifications_unknown": "Notification status is unknown",
            "notifications_error": "Could not enable notifications. Check iPhone Settings and try again.",
            "care_free_year": "Included free for every pilgrim during the first year",
            "chat_send_failed": "Message was not sent. %@",
            "error_invalid_response": "The server returned an invalid response.",
            "error_status": "Server request failed (%d).",
            "error_decoding": "Could not read the server response.",
            "error_missing_booking_token": "The booking was created without an access token. Please create a new booking or contact iumrah Care.",
            "error_offline": "No internet connection. Check your connection and try again.",
            "error_timeout": "The request took too long. Please try again.",
            "error_network": "A network error occurred. Please try again.",
            "error_unknown": "Something went wrong. Please try again.",
            "flight_search_failed": "Search did not finish",
            "flight_challenge_title": "Verification required",
            "flight_challenge_body": "%@ requires a human verification. Complete it and retry the search. The session stays on this iPhone.",
            "flight_select_hotel_first": "Choose a hotel first.",
            "home_philosophy_title": "Not a tour. Your own Umrah.",
            "home_philosophy_body": "iumrah helps you organize Umrah for yourself, your family or friends — without a large group, while Care stays connected to the same trip.",
            "home_connected_title": "One trip. Everything connected.",
            "home_connected_body": "Flight → hotel → transfer → Umrah → Care. One calm journey instead of scattered services.",
            "price_per_person": "/ person",
            "drawer_greeting": "Assalamu alaikum",
            "drawer_welcome": "Welcome to iumrah",
            "drawer_chats": "Chats",
            "flight_error_service": "The trip calculation service is temporarily unavailable.",
            "flight_error_makkah": "The Makkah hotel price is not configured yet.",
            "flight_error_madinah": "The Madinah hotel price is not configured yet for this route.",
            "flight_error_outbound": "The outbound flight selection is no longer available. Search flights again.",
            "flight_error_fare_scope": "Could not verify the fare type from %@.",
            "flight_error_candidate": "The flight system can no longer find the selected option %@.",
            "flight_error_minimum": "Only %d verified options remained; at least %d are required.",
            "booking_home_subtitle": "Every trip, its status and iumrah Care stay together in one place.",
            "care_metric_answers": "Answers",
            "care_metric_updates": "Updates",
            "care_metric_care": "Care",
            "story_kicker": "BORN IN MAKKAH",
            "story_title": "Why iumrah Project",
            "story_intro": "iumrah did not begin as an idea for another travel service. It began with experience.",
            "story_p1": "After spending more than a year in Makkah and staying close to pilgrims, we kept seeing the same problem: a journey people travel thousands of kilometres for too often depended on a large group, intermediaries and someone else’s schedule.",
            "story_p2": "We wanted to build another path — one where a person can perform Umrah independently, with family or friends, without being left alone with the organisation of the journey.",
            "story_why_project_title": "Why Project",
            "story_why_project_body": "Because this path should never be considered finished. With every trip, every question and every new pilgrim need, iumrah should become better.",
            "story_mission_title": "Our task",
            "story_mission_body": "Do not make the pilgrim understand the system. The system should understand the pilgrim’s trip.",
            "story_nav_title": "Our story",
            "recommended_madinah_hotel": "iumrah selected hotel · Madinah",
            "error_booking_access": "Booking access could not be verified.",
            "error_rate_limit": "Too many messages were sent. Try again in a minute.",
            "error_chat_load": "Could not load the chat.",
            "error_chat_send": "Could not send the message.",
            "error_service_unavailable": "The service is temporarily unavailable.",
            "error_invalid_request": "The request could not be processed.",
            "error_server_named": "Server error: %@.",
            "flight_error_insufficient": "Only %d verified flight options were found; at least %d are required.",
            "flight_error_insufficient_challenge": "Only %d verified flight options were found; at least %d are required. Verification is required for: %@.",
            "flight_bot_invalid_page": "The airline page could not be prepared.",
            "flight_bot_challenge": "Human verification is required by %@.",
            "flight_bot_no_candidates": "The provider returned no readable flight options.",
            "flight_bot_timeout": "The flight provider took too long to respond.",
            "umrah_coming": "Step-by-step Umrah guidance will appear here in a future update."

        ],
        "ru": [
            "tab_home": "Главная",
            "tab_hotels": "Отели",
            "tab_booking": "Бронирование",
            "tab_care": "Care",
            "tab_umrah": "Умра",
            "profile_placeholder": "Ваш профиль",
            "profile_subtitle_empty": "Добавьте имя и контакты",
            "profile_subtitle_ready": "Профиль паломника",
            "settings_title": "Настройки",
            "settings_done": "Готово",
            "profile_section": "Профиль",
            "language_section": "Язык",
            "appearance_section": "Оформление",
            "field_first_name": "Имя",
            "field_last_name": "Фамилия",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Язык приложения",
            "theme_label": "Тема",
            "appearance_system": "Как на iPhone",
            "appearance_light": "Светлая",
            "appearance_dark": "Тёмная",
            "language_russian": "Русский",
            "language_english": "Английский",
            "language_uzbek": "Узбекский",
            "language_uzbek_cyr": "Узбекский · кириллица",
            "home_hero_kicker": "ВАША УМРА",
            "home_hero_title": "Ваша Умра.\nВаш путь.",
            "home_hero_body": "Перелёт, проживание и поддержка — собраны вокруг вашей поездки, а не вокруг большой группы.",
            "home_hero_cta": "Собрать мою Умру",
            "home_hero_badge": "Итоговая стоимость показывается до бронирования",
            "hotels_title": "iumrah Hotel Space",
            "hotels_subtitle": "Отели, подобранные командой iumrah для паломников, которым важны надёжный сервис, удобная локация и более спокойное проживание.",
            "hotels_note": "iumrah не владеет этими отелями. Мы внимательно отбираем и проверяем объекты, которые подходят нашим паломникам.",
            "hotels_makkah": "Подборка для Мекки",
            "city_makkah": "Мекка",
            "city_madinah": "Медина",
            "flight_airline_unknown": "Авиакомпания",
            "hotels_madinah": "Подборка для Медины",
            "hotels_selected_badge": "Подобрано iumrah",
            "hotels_load_error": "Сейчас не удалось загрузить отели.",
            "booking_hero_kicker": "НОВАЯ ПОЕЗДКА",
            "booking_hero_title": "Соберите свою Умру",
            "booking_hero_body": "Выберите даты, людей и уровень поездки. Затем iumrah предложит отель и найдёт подходящие перелёты с прозрачной итоговой стоимостью пакета.",
            "booking_hero_cta": "Создать мою Умру",
            "booking_empty_title": "Бронирований пока нет",
            "booking_empty_body": "После подтверждения первая поездка появится здесь.",
            "trip_intro_kicker": "СОБЕРИТЕ СВОЮ УМРУ",
            "trip_intro_title": "Начнём с вашей поездки",
            "trip_intro_body": "Выберите маршрут, даты и людей. iumrah использует эти параметры, чтобы подобрать отель и найти подходящие перелёты.",
            "step_trip": "Поездка",
            "step_hotel": "Отель",
            "step_flight": "Перелёт",
            "step_ready": "Готово",
            "trip_continue_hotel": "Продолжить к отелю",
            "checkout_title": "Проверим вашу поездку",
            "checkout_subtitle": "Перед подтверждением iumrah ещё раз проверит доступность выбранного отеля и перелётов.",
            "next_title": "Что произойдёт дальше",
            "next_one": "Поездка получит защищённый номер",
            "next_two": "Начнётся проверка доступности",
            "next_three": "Статус появится во вкладке «Бронирование»",
            "next_four": "Чат iumrah Care будет связан с этой поездкой",
            "checkout_cta": "Проверить и создать бронирование",
            "success_title": "Поездка создана",
            "success_body": "Сейчас iumrah проверяет доступность. Статус поездки и чат поддержки уже связаны с этим номером.",
            "open_booking": "Открыть бронирование",
            "open_care": "Открыть iumrah Care",
            "profile_required_title": "Данные паломника",
            "profile_required_body": "Перед бронированием добавьте имя, фамилию и хотя бы один контакт, чтобы поддержка видела, кто именно оформляет поездку.",
            "save_continue": "Сохранить и продолжить",
            "care_title": "iumrah Care",
            "care_subtitle": "Поддержка сопровождает вашу поездку до, во время и после Умры.",
            "care_chats": "Ваши чаты",
            "care_chats_subtitle": "Каждый чат связан с конкретной поездкой, поэтому не нужно заново объяснять маршрут, даты и отель.",
            "care_locked_title": "Чат откроется после бронирования",
            "care_locked_body": "Соберите поездку и отправьте её на проверку доступности. После этого поддержка будет связана с вашим бронированием.",
            "care_promise_title": "Самостоятельно — не значит одному.",
            "care_promise_body": "До поездки, в дороге и во время Умры iumrah Care остаётся одной линией поддержки, связанной с вашей поездкой.",
            "chat_online": "онлайн",
            "chat_unavailable": "Чат недоступен",
            "chat_empty_title": "Начните разговор",
            "chat_empty_body": "Спросите о бронировании, рейсе, отеле, трансфере или маршруте.",
            "chat_placeholder": "Сообщение…",
            "chat_load": "Загружаем чат…",
            "chat_retry": "Повторить",
            "chat_you": "Вы",
            "chat_staff": "iumrah Care",
            "status_availability": "Проверяем наличие",
            "status_payment": "Ожидает оплаты",
            "status_confirmed": "Бронирование подтверждено",
            "status_ready": "Готово к поездке",
            "status_completed": "Поездка завершена",
            "detail_booking": "Бронирование",
            "detail_updates": "Статус обновляется автоматически",
            "detail_chat_cta": "Чат с iumrah Care",
            "detail_not_found": "Бронирование не найдено",
            "detail_dates": "Даты поездки",
            "detail_hotel": "Отель",
            "route_label": "Маршрут",
            "route_return": "Обратно",
            "total_for": "Итого за",
            "travelers": "путешественников",
            "back": "Назад",
            "profile_accessibility": "Профиль",
            "trip_origin_title": "Откуда начинается поездка",
            "trip_destination_title": "Куда хотите отправиться",
            "trip_route_picker": "Маршрут",
            "trip_arrival_title": "Куда прилететь сначала",
            "trip_arrival_picker": "Аэропорт прилёта",
            "trip_arrival_madinah_hint": "Сначала Медина. Обратный перелёт будем искать из Джидды.",
            "trip_arrival_jeddah_hint": "Сначала Мекка через Джидду. Обратный перелёт будем искать из Медины.",
            "trip_dates_title": "Когда хотите отправиться",
            "departure": "Вылет",
            "return": "Обратно",
            "trip_flexible_hint": "Гибкие даты помогают найти больше подходящих перелётов.",
            "trip_travelers_title": "Кто отправляется с вами",
            "trip_travelers_body": "Размещение и перелёты будут рассчитаны под вашу семью или компанию.",
            "adults": "Взрослые",
            "children": "Дети",
            "children_age": "2–11 лет",
            "infants": "Младенцы",
            "infants_age": "до 2 лет",
            "rooms": "Комнаты",
            "hotel_level": "Уровень отеля",
            "trip_format_title": "Какой формат поездки вам ближе",
            "popular": "ЧАЩЕ ВЫБИРАЮТ",
            "tier_economy": "Эконом",
            "tier_economy_subtitle": "Главное для спокойной Умры.",
            "tier_standard": "Стандарт",
            "tier_standard_subtitle": "Баланс расположения, комфорта и стоимости.",
            "tier_comfort": "Комфорт",
            "tier_comfort_subtitle": "Больше удобства каждый день.",
            "tier_luxury": "Люкс",
            "tier_luxury_subtitle": "Умра без компромиссов.",
            "flex_exact": "Точно",
            "flex_pm1": "±1 день",
            "flex_pm2": "±2 дня",
            "flex_weekend": "Выходные",
            "scope_makkah": "Только Мекка",
            "scope_both": "Мекка + Медина",
            "airport_jeddah": "Джидда",
            "airport_madinah": "Медина",
            "airport_jeddah_full": "Джидда · для Мекки",
            "airport_search_title": "Найдите аэропорт вылета",
            "airport_search_body": "Можно искать по городу, названию или трёхбуквенному коду аэропорта — например TAS, Ташкент, Стамбул.",
            "airport_none": "Ничего не найдено",
            "airport_none_body": "Попробуйте другой город или код аэропорта.",
            "airport_search_failed": "Сейчас не удалось выполнить поиск аэропортов.",
            "airport_title": "Аэропорт вылета",
            "close": "Закрыть",
            "primary_hotel_title": "Мы подобрали отель для вашей поездки",
            "primary_hotel_badge": "Рекомендует iumrah",
            "primary_hotel_subtitle": "Подходит выбранному уровню %@ и категории %d★. Вы можете оставить его или посмотреть другие варианты.",
            "primary_hotel_loading": "Загружаем каталог iumrah…",
            "retry": "Повторить",
            "primary_hotel_continue": "Продолжить с этим отелем",
            "primary_hotel_other": "Посмотреть другие варианты",
            "primary_hotel_empty": "В каталоге пока нет подходящего отеля.",
            "hotel_change_title": "Выбрать другой отель",
            "hotel_catalog_eyebrow": "Каталог iumrah",
            "hotel_change_body": "Здесь только отели, которые команда iumrah отобрала для паломников.",
            "selected": "Выбран",
            "flight_search_hero": "Лучшие билеты почти готовы",
            "flight_search_airlines": "Проверяем авиакомпании",
            "flight_search_dates": "Сравниваем подходящие даты",
            "flight_search_reprice": "Пересчитываем всю поездку",
            "flight_search_almost": "Лучшие билеты почти готовы",
            "flight_ready_title": "Готово",
            "flight_ready_body": "Подходящие варианты найдены, стоимость поездки пересчитана.",
            "flight_out_title": "Выберите перелёт",
            "flight_out_eyebrow": "Туда",
            "flight_out_body": "Каждая цена показывает итоговую стоимость всей Умры с этим вариантом перелёта.",
            "flight_choose_return": "Выбрать обратный рейс",
            "flight_return_title": "Выберите обратный перелёт",
            "flight_return_eyebrow": "Обратно",
            "flight_return_body": "Стоимость пересчитана вместе с выбранным рейсом туда и означает весь пакет целиком.",
            "flight_view_package": "Посмотреть готовую Умру",
            "flight_select_outbound_first": "Сначала выберите рейс туда.",
            "flight_nav_out": "Перелёт",
            "flight_nav_return": "Обратно",
            "flight_recommended": "Рекомендуем",
            "flight_whole_package": "Весь пакет",
            "flight_package_contents": "Отель + перелёты + услуги",
            "flight_direct": "Прямой",
            "flight_details_cta": "Подробнее о перелёте",
            "flight_details_title": "Детали перелёта",
            "flight_details_route": "%@ → %@",
            "flight_segment_count": "Рейс %d из %d",
            "flight_detail_duration": "Время в пути",
            "flight_detail_aircraft": "Самолёт",
            "flight_detail_cabin": "Класс",
            "flight_detail_operated_by": "Выполняет",
            "flight_detail_unknown": "Нет данных",
            "flight_terminal": "Терминал %@",
            "flight_layover_title": "Пересадка в %@",
            "flight_layover_airport_change": "Смена аэропорта в %@",
            "flight_layover_overnight": "Ночная пересадка",
            "flight_layover_summary": "%@ · пересадка %@",
            "flight_airport_change": "%@ · смена аэропорта · %@",
            "flight_duration_short": "%dч %dм",
            "flight_hours_short": "%dч",
            "flight_minutes_short": "%dм",
            "flight_cabin_economy": "Эконом",
            "flight_cabin_business": "Бизнес",
            "flight_cabin_premium": "Премиум-эконом",
            "flight_cabin_first": "Первый класс",
            "flight_details_price_note": "Это итоговая стоимость всей Умры на человека с этим перелётом. Цена билета отдельно не показывается.",
            "flight_stops": "Пересадок: %d",
            "challenge_open": "Пройти проверку",
            "flight_retry": "Повторить поиск",
            "final_nav_title": "Готовая поездка",
            "final_calculating": "Считаем итоговую стоимость…",
            "final_title": "Ваша Умра готова",
            "final_body": "Мы собрали поездку по вашим датам и предпочтениям. Перелёты, отель и выбранные услуги связаны в один пакет.",
            "final_price": "Итоговая стоимость",
            "final_total_group": "Всего за %d путешественников: %@",
            "final_price_note": "Это стоимость выбранного пакета целиком",
            "final_in_trip": "В вашей поездке",
            "final_outbound": "Перелёт туда",
            "final_hotel": "Отель",
            "final_transfer": "Трансферы и услуги",
            "final_return": "Перелёт обратно",
            "final_care": "iumrah Care",
            "final_visa": "Виза",
            "included": "Включено",
            "final_before": "Перед бронированием",
            "final_check_one": "Ещё раз проверим доступность",
            "final_check_two": "Условия доступны до подтверждения",
            "final_check_three": "После бронирования поездка появится в «Бронирование» и iumrah Care",
            "final_book_cta": "Забронировать мою Умру",
            "notifications_title": "Уведомления о поездке",
            "notifications_enable": "Включить уведомления",
            "notifications_enabled": "Уведомления подключены",
            "notifications_not_determined": "Уведомления ещё не включены",
            "notifications_denied": "Уведомления отключены в настройках iPhone",
            "notifications_registering": "Разрешено · регистрируем устройство",
            "notifications_provisional": "Тихие уведомления подключены",
            "notifications_ephemeral": "Временное разрешение активно",
            "notifications_unknown": "Статус уведомлений неизвестен",
            "notifications_error": "Не удалось включить уведомления. Проверьте настройки iPhone и повторите попытку.",
            "care_free_year": "Первый год включено бесплатно для каждого паломника",
            "chat_send_failed": "Сообщение не отправлено. %@",
            "error_invalid_response": "Сервер вернул некорректный ответ.",
            "error_status": "Ошибка сервера (%d).",
            "error_decoding": "Не удалось прочитать данные сервера.",
            "error_missing_booking_token": "Бронирование создано без токена доступа. Создайте новое бронирование или обратитесь в iumrah Care.",
            "error_offline": "Нет подключения к интернету. Проверьте соединение и повторите попытку.",
            "error_timeout": "Сервер отвечает слишком долго. Повторите попытку.",
            "error_network": "Произошла ошибка сети. Повторите попытку.",
            "error_unknown": "Что-то пошло не так. Повторите попытку.",
            "flight_search_failed": "Поиск не завершён",
            "flight_challenge_title": "Нужна проверка",
            "flight_challenge_body": "%@ запросил человеческую проверку. Пройдите её и повторите поиск. Сессия сохраняется на этом iPhone.",
            "flight_select_hotel_first": "Сначала выберите отель.",
            "home_philosophy_title": "Не тур. Ваша собственная Умра.",
            "home_philosophy_body": "iumrah помогает организовать Умру для себя, семьи или друзей — без большой группы, а Care остаётся связан с той же поездкой.",
            "home_connected_title": "Одна поездка. Всё связано.",
            "home_connected_body": "Перелёт → отель → трансфер → Умра → Care. Одна спокойная поездка вместо разрозненных сервисов.",
            "price_per_person": "/ чел.",
            "drawer_greeting": "Ассаляму алейкум",
            "drawer_welcome": "Добро пожаловать в iumrah",
            "drawer_chats": "Чаты",
            "flight_error_service": "Сервис расчёта поездки временно недоступен.",
            "flight_error_makkah": "Для Мекки пока не настроена цена основного отеля.",
            "flight_error_madinah": "Для этого маршрута пока не настроена цена основного отеля в Медине.",
            "flight_error_outbound": "Выбранный рейс туда больше недоступен. Повторите поиск перелёта.",
            "flight_error_fare_scope": "Не удалось подтвердить тип тарифа у %@.",
            "flight_error_candidate": "Система перелётов больше не видит выбранный вариант %@.",
            "flight_error_minimum": "После проверки осталось %d вариантов; требуется минимум %d.",
            "booking_home_subtitle": "Все поездки, их статусы и iumrah Care остаются в одном месте.",
            "care_metric_answers": "Ответы",
            "care_metric_updates": "Статус",
            "care_metric_care": "Забота",
            "story_kicker": "ПРОЕКТ, РОЖДЁННЫЙ В МЕККЕ",
            "story_title": "Почему iumrah Project",
            "story_intro": "iumrah появилась не из идеи создать ещё один туристический сервис. Она появилась из опыта.",
            "story_p1": "Проведя больше года в Мекке и находясь рядом с паломниками, мы снова и снова видели одну проблему: поездка, ради которой человек преодолевает тысячи километров, слишком часто становилась зависимой от большой группы, посредников и чужого расписания.",
            "story_p2": "Мы захотели построить другой путь — чтобы человек мог совершить Умру самостоятельно, с семьёй или друзьями, но при этом не оставался один на один с организацией поездки.",
            "story_why_project_title": "Почему Project",
            "story_why_project_body": "Потому что этот путь не должен однажды считаться законченным. С каждой поездкой, каждым вопросом и каждой новой потребностью паломника iumrah должна становиться лучше.",
            "story_mission_title": "Наша задача",
            "story_mission_body": "Не заставлять паломника разбираться в системе. Система должна разбираться в его поездке.",
            "story_nav_title": "Наша история",
            "recommended_madinah_hotel": "Отель, подобранный iumrah · Медина",
            "error_booking_access": "Не удалось подтвердить доступ к бронированию.",
            "error_rate_limit": "Отправлено слишком много сообщений. Повторите через минуту.",
            "error_chat_load": "Не удалось загрузить чат.",
            "error_chat_send": "Не удалось отправить сообщение.",
            "error_service_unavailable": "Сервис временно недоступен.",
            "error_invalid_request": "Не удалось обработать запрос.",
            "error_server_named": "Ошибка сервера: %@.",
            "flight_error_insufficient": "Найдено только %d подтверждённых вариантов перелёта; требуется минимум %d.",
            "flight_error_insufficient_challenge": "Найдено только %d подтверждённых вариантов; требуется минимум %d. Нужна проверка у: %@.",
            "flight_bot_invalid_page": "Не удалось подготовить страницу авиакомпании.",
            "flight_bot_challenge": "%@ запросил человеческую проверку.",
            "flight_bot_no_candidates": "Провайдер не вернул читаемых вариантов перелёта.",
            "flight_bot_timeout": "Провайдер перелётов слишком долго не отвечает.",
            "umrah_coming": "Пошаговое сопровождение Умры появится здесь в одном из следующих обновлений."

        ],
        "uz": [
            "tab_home": "Asosiy",
            "tab_hotels": "Mehmonxonalar",
            "tab_booking": "Bron",
            "tab_care": "Care",
            "tab_umrah": "Umra",
            "profile_placeholder": "Profilingiz",
            "profile_subtitle_empty": "Ism va kontaktlarni qo‘shing",
            "profile_subtitle_ready": "Ziyoratchi profili",
            "settings_title": "Sozlamalar",
            "settings_done": "Tayyor",
            "profile_section": "Profil",
            "language_section": "Til",
            "appearance_section": "Ko‘rinish",
            "field_first_name": "Ism",
            "field_last_name": "Familiya",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Ilova tili",
            "theme_label": "Mavzu",
            "appearance_system": "iPhone kabi",
            "appearance_light": "Yorug‘",
            "appearance_dark": "Qorong‘i",
            "language_russian": "Ruscha",
            "language_english": "Inglizcha",
            "language_uzbek": "O‘zbekcha",
            "language_uzbek_cyr": "O‘zbekcha · kirill",
            "home_hero_kicker": "SIZNING UMRANGIZ",
            "home_hero_title": "Sizning Umrangiz.\nSizning yo‘lingiz.",
            "home_hero_body": "Parvoz, turar joy va yordam — katta guruh atrofida emas, aynan safaringiz atrofida jamlanadi.",
            "home_hero_cta": "Umramni yig‘ish",
            "home_hero_badge": "Yakuniy narx bron qilishdan oldin ko‘rsatiladi",
            "hotels_title": "iumrah Hotel Space",
            "hotels_subtitle": "iumrah jamoasi tomonidan ziyoratchilar uchun tanlangan mehmonxonalar: ishonchli xizmat, qulay joylashuv va xotirjam yashash uchun.",
            "hotels_note": "iumrah bu mehmonxonalarga egalik qilmaydi. Biz ziyoratchilarimizga mos joylarni sinchiklab tanlaymiz va kuzatib boramiz.",
            "hotels_makkah": "Makka uchun tanlov",
            "city_makkah": "Makka",
            "city_madinah": "Madina",
            "flight_airline_unknown": "Aviakompaniya",
            "hotels_madinah": "Madina uchun tanlov",
            "hotels_selected_badge": "iumrah tanlovi",
            "hotels_load_error": "Hozir mehmonxonalarni yuklab bo‘lmadi.",
            "booking_hero_kicker": "YANGI SAFAR",
            "booking_hero_title": "Umrangizni yig‘ing",
            "booking_hero_body": "Sanalar, odamlar va safar darajasini tanlang. So‘ng iumrah mehmonxona tavsiya qiladi va aniq paket narxi bilan mos parvozlarni topadi.",
            "booking_hero_cta": "Umramni yaratish",
            "booking_empty_title": "Hozircha bron yo‘q",
            "booking_empty_body": "Tasdiqlangandan so‘ng birinchi safaringiz shu yerda ko‘rinadi.",
            "trip_intro_kicker": "UMRANGIZNI YIG‘ING",
            "trip_intro_title": "Safaringizdan boshlaymiz",
            "trip_intro_body": "Yo‘nalish, sanalar va yo‘lovchilarni tanlang. iumrah shu ma’lumotlar asosida mehmonxona va mos parvozlarni topadi.",
            "step_trip": "Safar",
            "step_hotel": "Mehmonxona",
            "step_flight": "Parvoz",
            "step_ready": "Tayyor",
            "trip_continue_hotel": "Mehmonxonaga o‘tish",
            "checkout_title": "Safaringizni tekshiramiz",
            "checkout_subtitle": "Tasdiqlashdan oldin iumrah tanlangan mehmonxona va parvozlar mavjudligini yana bir bor tekshiradi.",
            "next_title": "Keyin nima bo‘ladi",
            "next_one": "Safarga himoyalangan bron raqami beriladi",
            "next_two": "Mavjudlik tekshiruvi boshlanadi",
            "next_three": "Holat Bron bo‘limida paydo bo‘ladi",
            "next_four": "iumrah Care chati shu safarga ulanadi",
            "checkout_cta": "Tekshirish va bron yaratish",
            "success_title": "Safar yaratildi",
            "success_body": "Hozir iumrah mavjudlikni tekshirmoqda. Safar holati va yordam chati shu safarga bog‘landi.",
            "open_booking": "Bronni ochish",
            "open_care": "iumrah Care'ni ochish",
            "profile_required_title": "Ziyoratchi ma’lumotlari",
            "profile_required_body": "Bron qilishdan oldin ism, familiya va kamida bitta kontaktni kiriting, shunda yordam jamoasi ziyoratchini taniydi.",
            "save_continue": "Saqlash va davom etish",
            "care_title": "iumrah Care",
            "care_subtitle": "Yordam Umradan oldin, davomida va keyin safaringiz bilan qoladi.",
            "care_chats": "Chatlaringiz",
            "care_chats_subtitle": "Har bir chat aniq safarga bog‘langan, shuning uchun yo‘nalish, sanalar va mehmonxonani qayta tushuntirish shart emas.",
            "care_locked_title": "Chat bron yaratilgach ochiladi",
            "care_locked_body": "Safaringizni yig‘ing va mavjudlikka yuboring. Shundan keyin yordam jamoasi broningizga ulanadi.",
            "care_promise_title": "Mustaqil — yolg‘iz degani emas.",
            "care_promise_body": "Safargacha, yo‘lda va Umra davomida iumrah Care safaringizga bog‘langan yagona yordam liniyasi bo‘lib qoladi.",
            "chat_online": "online",
            "chat_unavailable": "Chat mavjud emas",
            "chat_empty_title": "Suhbatni boshlang",
            "chat_empty_body": "Bron, parvoz, mehmonxona, transfer yoki yo‘nalish bo‘yicha yozing.",
            "chat_placeholder": "Xabar…",
            "chat_load": "Chat yuklanmoqda…",
            "chat_retry": "Qayta urinish",
            "chat_you": "Siz",
            "chat_staff": "iumrah Care",
            "status_availability": "Mavjudlik tekshirilmoqda",
            "status_payment": "To‘lov kutilmoqda",
            "status_confirmed": "Bron tasdiqlandi",
            "status_ready": "Safarga tayyor",
            "status_completed": "Safar yakunlandi",
            "detail_booking": "Bron",
            "detail_updates": "Holat avtomatik yangilanadi",
            "detail_chat_cta": "iumrah Care bilan chat",
            "detail_not_found": "Bron topilmadi",
            "detail_dates": "Safar sanalari",
            "detail_hotel": "Mehmonxona",
            "route_label": "Yo‘nalish",
            "route_return": "Qaytish",
            "total_for": "Jami",
            "travelers": "yo‘lovchi uchun",
            "back": "Ortga",
            "profile_accessibility": "Profil",
            "trip_origin_title": "Safar qayerdan boshlanadi",
            "trip_destination_title": "Qayerga yo‘l olmoqchisiz",
            "trip_route_picker": "Yo‘nalish",
            "trip_arrival_title": "Avval qaysi aeroportga",
            "trip_arrival_picker": "Kelish aeroporti",
            "trip_arrival_madinah_hint": "Avval Madina. Qaytish reysi Jiddadan qidiriladi.",
            "trip_arrival_jeddah_hint": "Avval Makka Jidda orqali. Qaytish reysi Madinadan qidiriladi.",
            "trip_dates_title": "Qachon yo‘lga chiqmoqchisiz",
            "departure": "Jo‘nash",
            "return": "Qaytish",
            "trip_flexible_hint": "Moslashuvchan sanalar ko‘proq mos parvozlarni topishga yordam beradi.",
            "trip_travelers_title": "Siz bilan kim safar qiladi",
            "trip_travelers_body": "Joylashuv va parvozlar oilangiz yoki guruhingiz uchun hisoblanadi.",
            "adults": "Kattalar",
            "children": "Bolalar",
            "children_age": "2–11 yosh",
            "infants": "Go‘daklar",
            "infants_age": "2 yoshgacha",
            "rooms": "Xonalar",
            "hotel_level": "Mehmonxona darajasi",
            "trip_format_title": "Qaysi safar formati sizga mos",
            "popular": "KO‘P TANLANADI",
            "tier_economy": "Ekonom",
            "tier_economy_subtitle": "Tinch Umra uchun eng zarur narsalar.",
            "tier_standard": "Standart",
            "tier_standard_subtitle": "Joylashuv, qulaylik va narx muvozanati.",
            "tier_comfort": "Komfort",
            "tier_comfort_subtitle": "Har kuni ko‘proq qulaylik.",
            "tier_luxury": "Lyuks",
            "tier_luxury_subtitle": "Murosasiz Umra.",
            "flex_exact": "Aniq",
            "flex_pm1": "±1 kun",
            "flex_pm2": "±2 kun",
            "flex_weekend": "Dam olish kunlari",
            "scope_makkah": "Faqat Makka",
            "scope_both": "Makka + Madina",
            "airport_jeddah": "Jidda",
            "airport_madinah": "Madina",
            "airport_jeddah_full": "Jidda · Makka uchun",
            "airport_search_title": "Jo‘nash aeroportini toping",
            "airport_search_body": "Shahar, aeroport nomi yoki uch harfli kod bo‘yicha qidiring — masalan TAS, Toshkent, Istanbul.",
            "airport_none": "Hech narsa topilmadi",
            "airport_none_body": "Boshqa shahar yoki aeroport kodini kiriting.",
            "airport_search_failed": "Hozir aeroportlarni qidirib bo‘lmadi.",
            "airport_title": "Jo‘nash aeroporti",
            "close": "Yopish",
            "primary_hotel_title": "Safaringiz uchun mehmonxona tanladik",
            "primary_hotel_badge": "iumrah tavsiya qiladi",
            "primary_hotel_subtitle": "Tanlangan %@ darajasi va %d★ toifasiga mos. Uni qoldirishingiz yoki boshqa variantlarni ko‘rishingiz mumkin.",
            "primary_hotel_loading": "iumrah katalogi yuklanmoqda…",
            "retry": "Qayta urinish",
            "primary_hotel_continue": "Shu mehmonxona bilan davom etish",
            "primary_hotel_other": "Boshqa variantlarni ko‘rish",
            "primary_hotel_empty": "Katalogda hozircha mos mehmonxona yo‘q.",
            "hotel_change_title": "Boshqa mehmonxonani tanlash",
            "hotel_catalog_eyebrow": "iumrah katalogi",
            "hotel_change_body": "Bu yerda faqat iumrah ziyoratchilar uchun tanlagan mehmonxonalar ko‘rsatiladi.",
            "selected": "Tanlangan",
            "flight_search_hero": "Eng yaxshi chiptalar deyarli tayyor",
            "flight_search_airlines": "Aviakompaniyalarni tekshiryapmiz",
            "flight_search_dates": "Mos sanalarni solishtiryapmiz",
            "flight_search_reprice": "Butun safarni qayta hisoblayapmiz",
            "flight_search_almost": "Eng yaxshi chiptalar deyarli tayyor",
            "flight_ready_title": "Tayyor",
            "flight_ready_body": "Mos variantlar topildi va safar narxi qayta hisoblandi.",
            "flight_out_title": "Jo‘nash parvozini tanlang",
            "flight_out_eyebrow": "Borish",
            "flight_out_body": "Har bir narx shu parvoz bilan Umrangizning yakuniy umumiy narxini ko‘rsatadi.",
            "flight_choose_return": "Qaytish reysini tanlash",
            "flight_return_title": "Qaytish parvozini tanlang",
            "flight_return_eyebrow": "Qaytish",
            "flight_return_body": "Narx tanlangan borish reysi bilan birga qayta hisoblangan va butun paketni bildiradi.",
            "flight_view_package": "Tayyor Umramni ko‘rish",
            "flight_select_outbound_first": "Avval borish reysini tanlang.",
            "flight_nav_out": "Parvoz",
            "flight_nav_return": "Qaytish",
            "flight_recommended": "Tavsiya qilamiz",
            "flight_whole_package": "Butun paket",
            "flight_package_contents": "Mehmonxona + parvozlar + xizmatlar",
            "flight_direct": "To‘g‘ridan-to‘g‘ri",
            "flight_details_cta": "Parvoz tafsilotlari",
            "flight_details_title": "Parvoz tafsilotlari",
            "flight_details_route": "%@ → %@",
            "flight_segment_count": "%d-reys, jami %d ta",
            "flight_detail_duration": "Parvoz vaqti",
            "flight_detail_aircraft": "Samolyot",
            "flight_detail_cabin": "Klass",
            "flight_detail_operated_by": "Amalga oshiradi",
            "flight_detail_unknown": "Ma’lumot yo‘q",
            "flight_terminal": "%@-terminal",
            "flight_layover_title": "%@ shahrida ulanish",
            "flight_layover_airport_change": "%@ shahrida aeroport almashadi",
            "flight_layover_overnight": "Tungi ulanish",
            "flight_layover_summary": "%@ · %@ kutish",
            "flight_airport_change": "%@ · aeroport almashadi · %@",
            "flight_duration_short": "%dsoat %ddaq",
            "flight_hours_short": "%dsoat",
            "flight_minutes_short": "%ddaq",
            "flight_cabin_economy": "Ekonom",
            "flight_cabin_business": "Biznes",
            "flight_cabin_premium": "Premium ekonom",
            "flight_cabin_first": "Birinchi klass",
            "flight_details_price_note": "Bu shu parvoz bilan Umra paketining bir kishi uchun yakuniy narxi. Chipta narxi alohida ko‘rsatilmaydi.",
            "flight_stops": "%d ta to‘xtash",
            "challenge_open": "Tekshiruvdan o‘tish",
            "flight_retry": "Qidiruvni takrorlash",
            "final_nav_title": "Tayyor safar",
            "final_calculating": "Yakuniy narx hisoblanmoqda…",
            "final_title": "Umrangiz tayyor",
            "final_body": "Safarni sanalaringiz va istaklaringiz asosida tuzdik. Parvozlar, mehmonxona va tanlangan xizmatlar bitta paketga birlashtirildi.",
            "final_price": "Yakuniy narx",
            "final_total_group": "%d yo‘lovchi uchun jami: %@",
            "final_price_note": "Bu tanlangan paketning to‘liq narxi",
            "final_in_trip": "Safaringiz tarkibida",
            "final_outbound": "Borish parvozi",
            "final_hotel": "Mehmonxona",
            "final_transfer": "Transfer va xizmatlar",
            "final_return": "Qaytish parvozi",
            "final_care": "iumrah Care",
            "final_visa": "Viza",
            "included": "Kiritilgan",
            "final_before": "Bron qilishdan oldin",
            "final_check_one": "Mavjudlikni yana bir bor tekshiramiz",
            "final_check_two": "Shartlar tasdiqlashgacha ko‘rinadi",
            "final_check_three": "Bron qilingach safar Bron va iumrah Care bo‘limida paydo bo‘ladi",
            "final_book_cta": "Umramni bron qilish",
            "notifications_title": "Safar bildirishnomalari",
            "notifications_enable": "Bildirishnomalarni yoqish",
            "notifications_enabled": "Bildirishnomalar ulandi",
            "notifications_not_determined": "Bildirishnomalar hali yoqilmagan",
            "notifications_denied": "Bildirishnomalar iPhone sozlamalarida o‘chirilgan",
            "notifications_registering": "Ruxsat berildi · qurilma ro‘yxatdan o‘tmoqda",
            "notifications_provisional": "Sokin bildirishnomalar yoqilgan",
            "notifications_ephemeral": "Vaqtinchalik ruxsat faol",
            "notifications_unknown": "Bildirishnoma holati noma’lum",
            "notifications_error": "Bildirishnomalarni yoqib bo‘lmadi. iPhone sozlamalarini tekshirib, qayta urinib ko‘ring.",
            "care_free_year": "Birinchi yil har bir ziyoratchi uchun bepul kiritilgan",
            "chat_send_failed": "Xabar yuborilmadi. %@",
            "error_invalid_response": "Server noto‘g‘ri javob qaytardi.",
            "error_status": "Server xatosi (%d).",
            "error_decoding": "Server ma’lumotlarini o‘qib bo‘lmadi.",
            "error_missing_booking_token": "Bron kirish tokenisiz yaratildi. Yangi bron yarating yoki iumrah Care bilan bog‘laning.",
            "error_offline": "Internet aloqasi yo‘q. Ulanishni tekshirib, qayta urinib ko‘ring.",
            "error_timeout": "So‘rov juda uzoq davom etdi. Qayta urinib ko‘ring.",
            "error_network": "Tarmoq xatosi yuz berdi. Qayta urinib ko‘ring.",
            "error_unknown": "Nimadir xato ketdi. Qayta urinib ko‘ring.",
            "flight_search_failed": "Qidiruv yakunlanmadi",
            "flight_challenge_title": "Tekshiruv kerak",
            "flight_challenge_body": "%@ inson tekshiruvini so‘radi. Uni yakunlab, qidiruvni qayta boshlang. Sessiya shu iPhone’da saqlanadi.",
            "flight_select_hotel_first": "Avval mehmonxonani tanlang.",
            "home_philosophy_title": "Tur emas. O‘zingizning Umrangiz.",
            "home_philosophy_body": "iumrah Umrani o‘zingiz, oilangiz yoki do‘stlaringiz uchun katta guruhsiz tashkil qilishga yordam beradi, Care esa shu safarga bog‘langan qoladi.",
            "home_connected_title": "Bitta safar. Hammasi bog‘langan.",
            "home_connected_body": "Parvoz → mehmonxona → transfer → Umra → Care. Tarqoq xizmatlar o‘rniga bitta xotirjam safar.",
            "price_per_person": "/ kishi",
            "drawer_greeting": "Assalomu alaykum",
            "drawer_welcome": "iumrah’ga xush kelibsiz",
            "drawer_chats": "Chatlar",
            "flight_error_service": "Safar hisoblash xizmati vaqtincha ishlamayapti.",
            "flight_error_makkah": "Makka uchun asosiy mehmonxona narxi hali sozlanmagan.",
            "flight_error_madinah": "Bu yo‘nalish uchun Madinadagi asosiy mehmonxona narxi hali sozlanmagan.",
            "flight_error_outbound": "Tanlangan borish reysi endi mavjud emas. Parvozni qayta qidiring.",
            "flight_error_fare_scope": "%@ tarif turini tasdiqlab bo‘lmadi.",
            "flight_error_candidate": "Parvoz tizimi tanlangan %@ variantini topa olmadi.",
            "flight_error_minimum": "Tekshiruvdan keyin %d variant qoldi; kamida %d ta kerak.",
            "booking_home_subtitle": "Barcha safarlar, ularning holati va iumrah Care bitta joyda saqlanadi.",
            "care_metric_answers": "Javoblar",
            "care_metric_updates": "Holat",
            "care_metric_care": "G‘amxo‘rlik",
            "story_kicker": "MAKKADA TUG‘ILGAN LOYIHA",
            "story_title": "Nega iumrah Project",
            "story_intro": "iumrah yana bir sayohat xizmatini yaratish g‘oyasidan boshlanmagan. U tajribadan tug‘ilgan.",
            "story_p1": "Makkada bir yildan ortiq vaqt yashab, ziyoratchilar yonida bo‘lganimizda bir muammoni qayta-qayta ko‘rdik: odam minglab kilometr bosib keladigan safar ko‘pincha katta guruh, vositachilar va boshqalarning jadvaliga bog‘lanib qolardi.",
            "story_p2": "Biz boshqa yo‘lni qurishni istadik — inson Umrani mustaqil, oilasi yoki do‘stlari bilan ado eta olsin, lekin safarni tashkil qilishda yolg‘iz qolmasin.",
            "story_why_project_title": "Nega Project",
            "story_why_project_body": "Chunki bu yo‘l bir kun tugallangan deb hisoblanmasligi kerak. Har bir safar, har bir savol va ziyoratchining har bir yangi ehtiyoji bilan iumrah yaxshilanib borishi kerak.",
            "story_mission_title": "Bizning vazifamiz",
            "story_mission_body": "Ziyoratchini tizimni tushunishga majbur qilmaslik. Tizim uning safarini tushunishi kerak.",
            "story_nav_title": "Bizning hikoyamiz",
            "recommended_madinah_hotel": "iumrah tanlagan mehmonxona · Madina",
            "error_booking_access": "Bron ma’lumotlariga kirishni tasdiqlab bo‘lmadi.",
            "error_rate_limit": "Juda ko‘p xabar yuborildi. Bir daqiqadan keyin qayta urinib ko‘ring.",
            "error_chat_load": "Chatni yuklab bo‘lmadi.",
            "error_chat_send": "Xabarni yuborib bo‘lmadi.",
            "error_service_unavailable": "Xizmat vaqtincha ishlamayapti.",
            "error_invalid_request": "So‘rovni qayta ishlab bo‘lmadi.",
            "error_server_named": "Server xatosi: %@.",
            "flight_error_insufficient": "Faqat %d ta tasdiqlangan parvoz varianti topildi; kamida %d ta kerak.",
            "flight_error_insufficient_challenge": "Faqat %d ta tasdiqlangan variant topildi; kamida %d ta kerak. Quyidagilarda tekshiruv talab qilinadi: %@.",
            "flight_bot_invalid_page": "Aviakompaniya sahifasini tayyorlab bo‘lmadi.",
            "flight_bot_challenge": "%@ inson tekshiruvini talab qilmoqda.",
            "flight_bot_no_candidates": "Provayder o‘qib bo‘ladigan parvoz variantlarini qaytarmadi.",
            "flight_bot_timeout": "Parvoz provayderi juda uzoq javob bermadi.",
            "umrah_coming": "Umra bo‘yicha bosqichma-bosqich yo‘riqnoma keyingi yangilanishlardan birida shu yerga qo‘shiladi."

        ],
        "uz-cyrl": [
            "tab_home": "Асосий",
            "tab_hotels": "Отеллар",
            "tab_booking": "Брон",
            "tab_care": "Care",
            "tab_umrah": "Умра",
            "profile_placeholder": "Профилингиз",
            "profile_subtitle_empty": "Исм ва контактларни қўшинг",
            "profile_subtitle_ready": "Зиёратчи профили",
            "settings_title": "Созламалар",
            "settings_done": "Тайёр",
            "profile_section": "Профиль",
            "language_section": "Тил",
            "appearance_section": "Кўриниш",
            "field_first_name": "Исм",
            "field_last_name": "Фамилия",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Илова тили",
            "theme_label": "Мавзу",
            "appearance_system": "iPhone каби",
            "appearance_light": "Ёруғ",
            "appearance_dark": "Қоронғи",
            "language_russian": "Русча",
            "language_english": "Инглизча",
            "language_uzbek": "Ўзбекча",
            "language_uzbek_cyr": "Ўзбекча · кирилл",
            "home_hero_kicker": "СИЗНИНГ УМРАНГИЗ",
            "home_hero_title": "Сизнинг Умрангиз.\nСизнинг йўлингиз.",
            "home_hero_body": "Парвоз, яшаш ва ёрдам — катта гуруҳ атрофида эмас, айнан сафарингиз атрофида жамланади.",
            "home_hero_cta": "Умрамни йиғиш",
            "home_hero_badge": "Якуний нарх брон қилишдан олдин кўрсатилади",
            "hotels_title": "iumrah Hotel Space",
            "hotels_subtitle": "iumrah жамоаси томонидан зиёратчилар учун танланган отеллар: ишончли сервис, қулай жойлашув ва хотиржам яшаш учун.",
            "hotels_note": "iumrah бу отелларга эгалик қилмайди. Биз зиёратчиларимизга мос жойларни синчиклаб танлаймиз ва кузатиб борамиз.",
            "hotels_makkah": "Макка учун танлов",
            "city_makkah": "Макка",
            "city_madinah": "Мадина",
            "flight_airline_unknown": "Авиакомпания",
            "hotels_madinah": "Мадина учун танлов",
            "hotels_selected_badge": "iumrah танлови",
            "hotels_load_error": "Ҳозир отелларни юклаб бўлмади.",
            "booking_hero_kicker": "ЯНГИ САФАР",
            "booking_hero_title": "Умрангизни йиғинг",
            "booking_hero_body": "Саналар, одамлар ва сафар даражасини танланг. Сўнг iumrah меҳмонхона тавсия қилади ва аниқ пакет нархи билан мос парвозларни топади.",
            "booking_hero_cta": "Умрамни яратиш",
            "booking_empty_title": "Ҳозирча брон йўқ",
            "booking_empty_body": "Тасдиқлангандан сўнг биринчи сафарингиз шу ерда кўринади.",
            "trip_intro_kicker": "УМРАНГИЗНИ ЙИҒИНГ",
            "trip_intro_title": "Сафарингиздан бошлаймиз",
            "trip_intro_body": "Йўналиш, саналар ва йўловчиларни танланг. iumrah шу маълумотлар асосида меҳмонхона ва мос парвозларни топади.",
            "step_trip": "Сафар",
            "step_hotel": "Отель",
            "step_flight": "Парвоз",
            "step_ready": "Тайёр",
            "trip_continue_hotel": "Отелга ўтиш",
            "checkout_title": "Сафарингизни текширамиз",
            "checkout_subtitle": "Тасдиқлашдан олдин iumrah танланган отель ва парвозлар мавжудлигини яна бир бор текширади.",
            "next_title": "Кейин нима бўлади",
            "next_one": "Сафарга ҳимояланган брон рақами берилади",
            "next_two": "Мавжудлик текшируви бошланади",
            "next_three": "Ҳолат Брон бўлимида пайдо бўлади",
            "next_four": "iumrah Care чати шу сафарга уланади",
            "checkout_cta": "Текшириш ва брон яратиш",
            "success_title": "Сафар яратилди",
            "success_body": "Ҳозир iumrah мавжудликни текширмоқда. Сафар ҳолати ва ёрдам чати шу сафарга боғланди.",
            "open_booking": "Бронни очиш",
            "open_care": "iumrah Care'ни очиш",
            "profile_required_title": "Зиёратчи маълумотлари",
            "profile_required_body": "Брон қилишдан олдин исм, фамилия ва камида битта контактни киритинг, шунда ёрдам жамоаси зиёратчини танийди.",
            "save_continue": "Сақлаш ва давом этиш",
            "care_title": "iumrah Care",
            "care_subtitle": "Ёрдам Умрадан олдин, давомида ва кейин сафарингиз билан қолади.",
            "care_chats": "Чатларингиз",
            "care_chats_subtitle": "Ҳар бир чат аниқ сафарга боғланган, шунинг учун йўналиш, саналар ва отелни қайта тушунтириш шарт эмас.",
            "care_locked_title": "Чат брон яратилгандан кейин очилади",
            "care_locked_body": "Сафарингизни тузинг ва мавжудлик текширувига юборинг. Шундан кейин ёрдам жамоаси бронингизга уланади.",
            "care_promise_title": "Мустақил — ёлғиз дегани эмас.",
            "care_promise_body": "Сафаргача, йўлда ва Умра давомида iumrah Care сафарингизга боғланган ягона ёрдам линияси бўлиб қолади.",
            "chat_online": "онлайн",
            "chat_unavailable": "Чат мавжуд эмас",
            "chat_empty_title": "Суҳбатни бошланг",
            "chat_empty_body": "Брон, парвоз, отель, трансфер ёки йўналиш бўйича ёзинг.",
            "chat_placeholder": "Хабар…",
            "chat_load": "Чат юкланмоқда…",
            "chat_retry": "Қайта уриниш",
            "chat_you": "Сиз",
            "chat_staff": "iumrah Care",
            "status_availability": "Мавжудлик текширилмоқда",
            "status_payment": "Тўлов кутилмоқда",
            "status_confirmed": "Брон тасдиқланди",
            "status_ready": "Сафарга тайёр",
            "status_completed": "Сафар якунланди",
            "detail_booking": "Брон",
            "detail_updates": "Ҳолат автоматик янгиланади",
            "detail_chat_cta": "iumrah Care билан чат",
            "detail_not_found": "Брон топилмади",
            "detail_dates": "Сафар саналари",
            "detail_hotel": "Меҳмонхона",
            "route_label": "Йўналиш",
            "route_return": "Қайтиш",
            "total_for": "Жами",
            "travelers": "йўловчи учун",
            "back": "Ортга",
            "profile_accessibility": "Профиль",
            "trip_origin_title": "Сафар қаердан бошланади",
            "trip_destination_title": "Қаерга йўл олмоқчисиз",
            "trip_route_picker": "Йўналиш",
            "trip_arrival_title": "Аввал қайси аэропортга",
            "trip_arrival_picker": "Келиш аэропорти",
            "trip_arrival_madinah_hint": "Аввал Мадина. Қайтиш рейси Жиддадан қидирилади.",
            "trip_arrival_jeddah_hint": "Аввал Макка Жидда орқали. Қайтиш рейси Мадинадан қидирилади.",
            "trip_dates_title": "Қачон йўлга чиқмоқчисиз",
            "departure": "Жўнаш",
            "return": "Қайтиш",
            "trip_flexible_hint": "Мослашувчан саналар кўпроқ мос парвозларни топишга ёрдам беради.",
            "trip_travelers_title": "Сиз билан ким сафар қилади",
            "trip_travelers_body": "Жойлашув ва парвозлар оилангиз ёки гуруҳингиз учун ҳисобланади.",
            "adults": "Катталар",
            "children": "Болалар",
            "children_age": "2–11 ёш",
            "infants": "Гўдаклар",
            "infants_age": "2 ёшгача",
            "rooms": "Хоналар",
            "hotel_level": "Меҳмонхона даражаси",
            "trip_format_title": "Қайси сафар формати сизга мос",
            "popular": "КЎП ТАНЛАНАДИ",
            "tier_economy": "Эконом",
            "tier_economy_subtitle": "Тинч Умра учун энг зарур нарсалар.",
            "tier_standard": "Стандарт",
            "tier_standard_subtitle": "Жойлашув, қулайлик ва нарх мувозанати.",
            "tier_comfort": "Комфорт",
            "tier_comfort_subtitle": "Ҳар куни кўпроқ қулайлик.",
            "tier_luxury": "Люкс",
            "tier_luxury_subtitle": "Муросасиз Умра.",
            "flex_exact": "Аниқ",
            "flex_pm1": "±1 кун",
            "flex_pm2": "±2 кун",
            "flex_weekend": "Дам олиш кунлари",
            "scope_makkah": "Фақат Макка",
            "scope_both": "Макка + Мадина",
            "airport_jeddah": "Жидда",
            "airport_madinah": "Мадина",
            "airport_jeddah_full": "Жидда · Макка учун",
            "airport_search_title": "Жўнаш аэропортини топинг",
            "airport_search_body": "Шаҳар, аэропорт номи ёки уч ҳарфли код бўйича қидиринг — масалан TAS, Тошкент, Истанбул.",
            "airport_none": "Ҳеч нарса топилмади",
            "airport_none_body": "Бошқа шаҳар ёки аэропорт кодини киритинг.",
            "airport_search_failed": "Ҳозир аэропортларни қидириб бўлмади.",
            "airport_title": "Жўнаш аэропорти",
            "close": "Ёпиш",
            "primary_hotel_title": "Сафарингиз учун меҳмонхона танладик",
            "primary_hotel_badge": "iumrah тавсия қилади",
            "primary_hotel_subtitle": "Танланган %@ даражаси ва %d★ тоифасига мос. Уни қолдиришингиз ёки бошқа вариантларни кўришингиз мумкин.",
            "primary_hotel_loading": "iumrah каталоги юкланмоқда…",
            "retry": "Қайта уриниш",
            "primary_hotel_continue": "Шу меҳмонхона билан давом этиш",
            "primary_hotel_other": "Бошқа вариантларни кўриш",
            "primary_hotel_empty": "Каталогда ҳозирча мос меҳмонхона йўқ.",
            "hotel_change_title": "Бошқа меҳмонхонани танлаш",
            "hotel_catalog_eyebrow": "iumrah каталоги",
            "hotel_change_body": "Бу ерда фақат iumrah зиёратчилар учун танлаган меҳмонхоналар кўрсатилади.",
            "selected": "Танланган",
            "flight_search_hero": "Энг яхши чипталар деярли тайёр",
            "flight_search_airlines": "Авиакомпанияларни текширяпмиз",
            "flight_search_dates": "Мос саналарни солиштиряпмиз",
            "flight_search_reprice": "Бутун сафарни қайта ҳисоблаяпмиз",
            "flight_search_almost": "Энг яхши чипталар деярли тайёр",
            "flight_ready_title": "Тайёр",
            "flight_ready_body": "Мос вариантлар топилди ва сафар нархи қайта ҳисобланди.",
            "flight_out_title": "Жўнаш парвозини танланг",
            "flight_out_eyebrow": "Бориш",
            "flight_out_body": "Ҳар бир нарх шу парвоз билан Умрангизнинг якуний умумий нархини кўрсатади.",
            "flight_choose_return": "Қайтиш рейсини танлаш",
            "flight_return_title": "Қайтиш парвозини танланг",
            "flight_return_eyebrow": "Қайтиш",
            "flight_return_body": "Нарх танланган бориш рейси билан бирга қайта ҳисобланган ва бутун пакетни билдиради.",
            "flight_view_package": "Тайёр Умрамни кўриш",
            "flight_select_outbound_first": "Аввал бориш рейсини танланг.",
            "flight_nav_out": "Парвоз",
            "flight_nav_return": "Қайтиш",
            "flight_recommended": "Тавсия қиламиз",
            "flight_whole_package": "Бутун пакет",
            "flight_package_contents": "Меҳмонхона + парвозлар + хизматлар",
            "flight_direct": "Тўғридан-тўғри",
            "flight_details_cta": "Парвоз тафсилотлари",
            "flight_details_title": "Парвоз тафсилотлари",
            "flight_details_route": "%@ → %@",
            "flight_segment_count": "%d-рейс, жами %d та",
            "flight_detail_duration": "Парвоз вақти",
            "flight_detail_aircraft": "Самолёт",
            "flight_detail_cabin": "Класс",
            "flight_detail_operated_by": "Амалга оширади",
            "flight_detail_unknown": "Маълумот йўқ",
            "flight_terminal": "%@-терминал",
            "flight_layover_title": "%@ шаҳрида уланиш",
            "flight_layover_airport_change": "%@ шаҳрида аэропорт алмашади",
            "flight_layover_overnight": "Тунги уланиш",
            "flight_layover_summary": "%@ · %@ кутиш",
            "flight_airport_change": "%@ · аэропорт алмашади · %@",
            "flight_duration_short": "%dсоат %dдақ",
            "flight_hours_short": "%dсоат",
            "flight_minutes_short": "%dдақ",
            "flight_cabin_economy": "Эконом",
            "flight_cabin_business": "Бизнес",
            "flight_cabin_premium": "Премиум эконом",
            "flight_cabin_first": "Биринчи класс",
            "flight_details_price_note": "Бу шу парвоз билан Умра пакетининг бир киши учун якуний нархи. Чипта нархи алоҳида кўрсатилмайди.",
            "flight_stops": "%d та тўхташ",
            "challenge_open": "Текширувдан ўтиш",
            "flight_retry": "Қидирувни такрорлаш",
            "final_nav_title": "Тайёр сафар",
            "final_calculating": "Якуний нарх ҳисобланмоқда…",
            "final_title": "Умрангиз тайёр",
            "final_body": "Сафарни саналарингиз ва истакларингиз асосида туздик. Парвозлар, меҳмонхона ва танланган хизматлар битта пакетга бирлаштирилди.",
            "final_price": "Якуний нарх",
            "final_total_group": "%d йўловчи учун жами: %@",
            "final_price_note": "Бу танланган пакетнинг тўлиқ нархи",
            "final_in_trip": "Сафарингиз таркибида",
            "final_outbound": "Бориш парвози",
            "final_hotel": "Меҳмонхона",
            "final_transfer": "Трансфер ва хизматлар",
            "final_return": "Қайтиш парвози",
            "final_care": "iumrah Care",
            "final_visa": "Виза",
            "included": "Киритилган",
            "final_before": "Брон қилишдан олдин",
            "final_check_one": "Мавжудликни яна бир бор текширамиз",
            "final_check_two": "Шартлар тасдиқлашгача кўринади",
            "final_check_three": "Брон қилингач сафар Брон ва iumrah Care бўлимида пайдо бўлади",
            "final_book_cta": "Умрамни брон қилиш",
            "notifications_title": "Сафар билдиришномалари",
            "notifications_enable": "Билдиришномаларни ёқиш",
            "notifications_enabled": "Билдиришномалар уланди",
            "notifications_not_determined": "Билдиришномалар ҳали ёқилмаган",
            "notifications_denied": "Билдиришномалар iPhone созламаларида ўчирилган",
            "notifications_registering": "Рухсат берилди · қурилма рўйхатдан ўтмоқда",
            "notifications_provisional": "Сокин билдиришномалар ёқилган",
            "notifications_ephemeral": "Вақтинчалик рухсат фаол",
            "notifications_unknown": "Билдиришнома ҳолати номаълум",
            "notifications_error": "Билдиришномаларни ёқиб бўлмади. iPhone созламаларини текшириб, қайта уриниб кўринг.",
            "care_free_year": "Биринчи йил ҳар бир зиёратчи учун бепул киритилган",
            "chat_send_failed": "Хабар юборилмади. %@",
            "error_invalid_response": "Сервер нотўғри жавоб қайтарди.",
            "error_status": "Сервер хатоси (%d).",
            "error_decoding": "Сервер маълумотларини ўқиб бўлмади.",
            "error_missing_booking_token": "Брон кириш токенисиз яратилди. Янги брон яратинг ёки iumrah Care билан боғланинг.",
            "error_offline": "Интернет алоқаси йўқ. Уланишни текшириб, қайта уриниб кўринг.",
            "error_timeout": "Сўров жуда узоқ давом этди. Қайта уриниб кўринг.",
            "error_network": "Тармоқ хатоси юз берди. Қайта уриниб кўринг.",
            "error_unknown": "Нимадир хато кетди. Қайта уриниб кўринг.",
            "flight_search_failed": "Қидирув якунланмади",
            "flight_challenge_title": "Текширув керак",
            "flight_challenge_body": "%@ инсон текширувини сўради. Уни якунлаб, қидирувни қайта бошланг. Сессия шу iPhone’да сақланади.",
            "flight_select_hotel_first": "Аввал меҳмонхонани танланг.",
            "home_philosophy_title": "Тур эмас. Ўзингизнинг Умрангиз.",
            "home_philosophy_body": "iumrah Умрани ўзингиз, оилангиз ёки дўстларингиз учун катта гуруҳсиз ташкил қилишга ёрдам беради, Care эса шу сафарга боғланган қолади.",
            "home_connected_title": "Битта сафар. Ҳаммаси боғланган.",
            "home_connected_body": "Парвоз → меҳмонхона → трансфер → Умра → Care. Тарқоқ хизматлар ўрнига битта хотиржам сафар.",
            "price_per_person": "/ киши",
            "drawer_greeting": "Ассалому алайкум",
            "drawer_welcome": "iumrah’га хуш келибсиз",
            "drawer_chats": "Чатлар",
            "flight_error_service": "Сафар ҳисоблаш хизмати вақтинча ишламаяпти.",
            "flight_error_makkah": "Макка учун асосий меҳмонхона нархи ҳали созланмаган.",
            "flight_error_madinah": "Бу йўналиш учун Мадинадаги асосий меҳмонхона нархи ҳали созланмаган.",
            "flight_error_outbound": "Танланган бориш рейси энди мавжуд эмас. Парвозни қайта қидиринг.",
            "flight_error_fare_scope": "%@ тариф турини тасдиқлаб бўлмади.",
            "flight_error_candidate": "Парвоз тизими танланган %@ вариантини топа олмади.",
            "flight_error_minimum": "Текширувдан кейин %d вариант қолди; камида %d та керак.",
            "booking_home_subtitle": "Барча сафарлар, уларнинг ҳолати ва iumrah Care битта жойда сақланади.",
            "care_metric_answers": "Жавоблар",
            "care_metric_updates": "Ҳолат",
            "care_metric_care": "Ғамхўрлик",
            "story_kicker": "МАККАДА ТУҒИЛГАН ЛОЙИҲА",
            "story_title": "Нега iumrah Project",
            "story_intro": "iumrah яна бир саёҳат хизматини яратиш ғоясидан бошланмаган. У тажрибадан туғилган.",
            "story_p1": "Маккада бир йилдан ортиқ вақт яшаб, зиёратчилар ёнида бўлганимизда бир муаммони қайта-қайта кўрдик: одам минглаб километр босиб келадиган сафар кўпинча катта гуруҳ, воситачилар ва бошқаларнинг жадвалига боғланиб қоларди.",
            "story_p2": "Биз бошқа йўлни қуришни истадик — инсон Умрани мустақил, оиласи ёки дўстлари билан адо эта олсин, лекин сафарни ташкил қилишда ёлғиз қолмасин.",
            "story_why_project_title": "Нега Project",
            "story_why_project_body": "Чунки бу йўл бир кун тугалланган деб ҳисобланмаслиги керак. Ҳар бир сафар, ҳар бир савол ва зиёратчининг ҳар бир янги эҳтиёжи билан iumrah яхшиланиб бориши керак.",
            "story_mission_title": "Бизнинг вазифамиз",
            "story_mission_body": "Зиёратчини тизимни тушунишга мажбур қилмаслик. Тизим унинг сафарини тушуниши керак.",
            "story_nav_title": "Бизнинг ҳикоямиз",
            "recommended_madinah_hotel": "iumrah танлаган меҳмонхона · Мадина",
            "error_booking_access": "Брон маълумотларига киришни тасдиқлаб бўлмади.",
            "error_rate_limit": "Жуда кўп хабар юборилди. Бир дақиқадан кейин қайта уриниб кўринг.",
            "error_chat_load": "Чатни юклаб бўлмади.",
            "error_chat_send": "Хабарни юбориб бўлмади.",
            "error_service_unavailable": "Хизмат вақтинча ишламаяпти.",
            "error_invalid_request": "Сўровни қайта ишлаб бўлмади.",
            "error_server_named": "Сервер хатоси: %@.",
            "flight_error_insufficient": "Фақат %d та тасдиқланган парвоз варианти топилди; камида %d та керак.",
            "flight_error_insufficient_challenge": "Фақат %d та тасдиқланган вариант топилди; камида %d та керак. Қуйидагиларда текширув талаб қилинади: %@.",
            "flight_bot_invalid_page": "Авиакомпания саҳифасини тайёрлаб бўлмади.",
            "flight_bot_challenge": "%@ инсон текширувини талаб қилмоқда.",
            "flight_bot_no_candidates": "Провайдер ўқиб бўладиган парвоз вариантларини қайтармади.",
            "flight_bot_timeout": "Парвоз провайдери жуда узоқ жавоб бермади.",
            "umrah_coming": "Умра бўйича босқичма-босқич йўриқнома кейинги янгиланишлардан бирида шу ерга қўшилади."

        ]
    ]
}
