import Foundation

struct L10n {
    static func text(_ key: String, _ language: AppSettingsStore.Language) -> String {
        let code = language.rawValue
        return dictionary[code]?[key] ?? dictionary["en"]?[key] ?? key
    }

    static func status(_ raw: String, _ language: AppSettingsStore.Language) -> String {
        let normalized = raw.uppercased()
        switch normalized {
        case "AVAILABILITY_CHECK": return text("status_availability", language)
        case "PAYMENT_PENDING": return text("status_payment", language)
        case "BOOKING_CONFIRMED": return text("status_confirmed", language)
        case "READY_TO_TRAVEL": return text("status_ready", language)
        case "COMPLETED": return text("status_completed", language)
        default: return raw.replacingOccurrences(of: "_", with: " ").capitalized
        }
    }

    private static let dictionary: [String: [String: String]] = [
        "en": [
            "tab_home": "Home",
            "tab_hotels": "Hotels",
            "tab_booking": "Booking",
            "tab_care": "Care",
            "tab_umrah": "Umrah",
            "profile_placeholder": "Your profile",
            "profile_subtitle_empty": "Add your name and contacts",
            "profile_subtitle_ready": "Pilgrim profile",
            "settings_title": "Settings",
            "settings_done": "Done",
            "profile_section": "Profile",
            "language_section": "Language",
            "appearance_section": "Appearance",
            "field_first_name": "First name",
            "field_last_name": "Last name",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "App language",
            "theme_label": "Theme",
            "appearance_system": "Match iPhone",
            "appearance_light": "Light",
            "appearance_dark": "Dark",
            "language_russian": "Russian",
            "language_english": "English",
            "language_uzbek": "Uzbek",
            "language_uzbek_cyr": "Uzbek (Cyrillic)",
            "home_hero_kicker": "YOUR UMRAH",
            "home_hero_title": "Your Umrah.\nYour path.",
            "home_hero_body": "Flights, stay and support — organized around your trip, not around a large group.",
            "home_hero_cta": "Build my Umrah",
            "home_hero_badge": "Final price is shown before booking",
            "hotels_title": "Aiomra Hotel Space",
            "hotels_subtitle": "Hotels selected by the Aiomra team for pilgrims who want reliable service, a convenient location and a calmer stay.",
            "hotels_note": "Aiomra does not own these hotels. We carefully select and monitor properties that suit our pilgrims.",
            "hotels_makkah": "Makkah selection",
            "hotels_madinah": "Madinah selection",
            "hotels_selected_badge": "Selected by Aiomra",
            "hotels_load_error": "Could not load hotels right now.",
            "booking_hero_kicker": "NEW TRIP",
            "booking_hero_title": "Build your Umrah",
            "booking_hero_body": "Choose dates, travelers and a travel tier. Aiomra will then suggest a hotel and find matching flights with a clear package price.",
            "booking_hero_cta": "Create my Umrah",
            "booking_empty_title": "No bookings yet",
            "booking_empty_body": "After confirmation, your first trip will appear here.",
            "trip_intro_kicker": "BUILD YOUR UMRAH",
            "trip_intro_title": "Let's start with your trip",
            "trip_intro_body": "Choose route, dates and travelers. Aiomra uses these details to suggest a hotel and find suitable flights.",
            "step_trip": "Trip",
            "step_hotel": "Hotel",
            "step_flight": "Flight",
            "step_ready": "Ready",
            "trip_continue_hotel": "Continue to hotel",
            "checkout_title": "Let's verify your trip",
            "checkout_subtitle": "Before confirmation, Aiomra checks availability for your selected hotel and flights one more time.",
            "next_title": "What happens next",
            "next_one": "Your trip gets a protected booking ID",
            "next_two": "Availability checking starts",
            "next_three": "Status appears in Booking",
            "next_four": "Aiomra Care chat links to this trip",
            "checkout_cta": "Review and create booking",
            "success_title": "Trip created",
            "success_body": "Aiomra is now checking availability. Your status and support chat are already linked to this trip.",
            "open_booking": "Open booking",
            "open_care": "Open Aiomra Care",
            "profile_required_title": "Pilgrim details",
            "profile_required_body": "Before booking, please add your first name, last name and at least one contact so support can recognize the pilgrim.",
            "save_continue": "Save and continue",
            "care_title": "Aiomra Care",
            "care_subtitle": "Support stays with your trip before, during and after Umrah.",
            "care_chats": "Your chats",
            "care_chats_subtitle": "Each chat is linked to a specific trip, so there is no need to explain the route, dates and hotel again.",
            "care_locked_title": "Chat opens after booking",
            "care_locked_body": "Build your trip and send it for availability checking. After that, support will be linked to your booking.",
            "care_promise_title": "Independent does not mean alone.",
            "care_promise_body": "Before the trip, on the road and during Umrah, Aiomra Care remains one support line linked to your trip.",
            "chat_online": "online",
            "chat_unavailable": "Chat unavailable",
            "chat_empty_title": "Start the conversation",
            "chat_empty_body": "Ask about your booking, flight, hotel, transfer or route.",
            "chat_placeholder": "Message…",
            "chat_load": "Loading chat…",
            "chat_retry": "Retry",
            "chat_you": "You",
            "chat_staff": "Aiomra Care",
            "status_availability": "Checking availability",
            "status_payment": "Awaiting payment",
            "status_confirmed": "Booking confirmed",
            "status_ready": "Ready to travel",
            "status_completed": "Trip completed",
            "detail_booking": "Booking",
            "detail_updates": "Status updates automatically",
            "detail_chat_cta": "Chat with Aiomra Care",
            "detail_not_found": "Booking not found",
            "route_label": "Route",
            "route_return": "Return",
            "total_for": "Total for",
            "travelers": "travelers"
        ],
        "ru": [
            "tab_home": "Главная",
            "tab_hotels": "Отели",
            "tab_booking": "Бронирование",
            "tab_care": "Care",
            "tab_umrah": "Умра",
            "profile_placeholder": "Ваш профиль",
            "profile_subtitle_empty": "Добавьте имя и контакты",
            "profile_subtitle_ready": "Профиль паломника",
            "settings_title": "Настройки",
            "settings_done": "Готово",
            "profile_section": "Профиль",
            "language_section": "Язык",
            "appearance_section": "Оформление",
            "field_first_name": "Имя",
            "field_last_name": "Фамилия",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Язык приложения",
            "theme_label": "Тема",
            "appearance_system": "Как на iPhone",
            "appearance_light": "Светлая",
            "appearance_dark": "Тёмная",
            "language_russian": "Русский",
            "language_english": "Английский",
            "language_uzbek": "Узбекский",
            "language_uzbek_cyr": "Узбекский · кириллица",
            "home_hero_kicker": "ВАША УМРА",
            "home_hero_title": "Ваша Умра.\nВаш путь.",
            "home_hero_body": "Перелёт, проживание и поддержка — собраны вокруг вашей поездки, а не вокруг большой группы.",
            "home_hero_cta": "Собрать мою Умру",
            "home_hero_badge": "Итоговая стоимость показывается до бронирования",
            "hotels_title": "Aiomra Hotel Space",
            "hotels_subtitle": "Отели, подобранные командой Aiomra для паломников, которым важны надёжный сервис, удобная локация и более спокойное проживание.",
            "hotels_note": "Aiomra не владеет этими отелями. Мы внимательно отбираем и проверяем объекты, которые подходят нашим паломникам.",
            "hotels_makkah": "Подборка для Мекки",
            "hotels_madinah": "Подборка для Медины",
            "hotels_selected_badge": "Подобрано Aiomra",
            "hotels_load_error": "Сейчас не удалось загрузить отели.",
            "booking_hero_kicker": "НОВАЯ ПОЕЗДКА",
            "booking_hero_title": "Соберите свою Умру",
            "booking_hero_body": "Выберите даты, людей и уровень поездки. Затем Aiomra предложит отель и найдёт подходящие перелёты с прозрачной итоговой стоимостью пакета.",
            "booking_hero_cta": "Создать мою Умру",
            "booking_empty_title": "Бронирований пока нет",
            "booking_empty_body": "После подтверждения первая поездка появится здесь.",
            "trip_intro_kicker": "СОБЕРИТЕ СВОЮ УМРУ",
            "trip_intro_title": "Начнём с вашей поездки",
            "trip_intro_body": "Выберите маршрут, даты и людей. Aiomra использует эти параметры, чтобы подобрать отель и найти подходящие перелёты.",
            "step_trip": "Поездка",
            "step_hotel": "Отель",
            "step_flight": "Перелёт",
            "step_ready": "Готово",
            "trip_continue_hotel": "Продолжить к отелю",
            "checkout_title": "Проверим вашу поездку",
            "checkout_subtitle": "Перед подтверждением Aiomra ещё раз проверит доступность выбранного отеля и перелётов.",
            "next_title": "Что произойдёт дальше",
            "next_one": "Поездка получит защищённый номер",
            "next_two": "Начнётся проверка доступности",
            "next_three": "Статус появится во вкладке «Бронирование»",
            "next_four": "Чат Aiomra Care будет связан с этой поездкой",
            "checkout_cta": "Проверить и создать бронирование",
            "success_title": "Поездка создана",
            "success_body": "Сейчас Aiomra проверяет доступность. Статус поездки и чат поддержки уже связаны с этим номером.",
            "open_booking": "Открыть бронирование",
            "open_care": "Открыть Aiomra Care",
            "profile_required_title": "Данные паломника",
            "profile_required_body": "Перед бронированием добавьте имя, фамилию и хотя бы один контакт, чтобы поддержка видела, кто именно оформляет поездку.",
            "save_continue": "Сохранить и продолжить",
            "care_title": "Aiomra Care",
            "care_subtitle": "Поддержка сопровождает вашу поездку до, во время и после Умры.",
            "care_chats": "Ваши чаты",
            "care_chats_subtitle": "Каждый чат связан с конкретной поездкой, поэтому не нужно заново объяснять маршрут, даты и отель.",
            "care_locked_title": "Чат откроется после бронирования",
            "care_locked_body": "Соберите поездку и отправьте её на проверку доступности. После этого поддержка будет связана с вашим бронированием.",
            "care_promise_title": "Самостоятельно — не значит одному.",
            "care_promise_body": "До поездки, в дороге и во время Умры Aiomra Care остаётся одной линией поддержки, связанной с вашей поездкой.",
            "chat_online": "онлайн",
            "chat_unavailable": "Чат недоступен",
            "chat_empty_title": "Начните разговор",
            "chat_empty_body": "Спросите о бронировании, рейсе, отеле, трансфере или маршруте.",
            "chat_placeholder": "Сообщение…",
            "chat_load": "Загружаем чат…",
            "chat_retry": "Повторить",
            "chat_you": "Вы",
            "chat_staff": "Aiomra Care",
            "status_availability": "Проверяем наличие",
            "status_payment": "Ожидает оплаты",
            "status_confirmed": "Бронирование подтверждено",
            "status_ready": "Готово к поездке",
            "status_completed": "Поездка завершена",
            "detail_booking": "Бронирование",
            "detail_updates": "Статус обновляется автоматически",
            "detail_chat_cta": "Чат с Aiomra Care",
            "detail_not_found": "Бронирование не найдено",
            "route_label": "Маршрут",
            "route_return": "Обратно",
            "total_for": "Итого за",
            "travelers": "путешественников"
        ],
        "uz": [
            "tab_home": "Asosiy",
            "tab_hotels": "Mehmonxonalar",
            "tab_booking": "Bron",
            "tab_care": "Care",
            "tab_umrah": "Umra",
            "profile_placeholder": "Profilingiz",
            "profile_subtitle_empty": "Ism va kontaktlarni qo‘shing",
            "profile_subtitle_ready": "Ziyoratchi profili",
            "settings_title": "Sozlamalar",
            "settings_done": "Tayyor",
            "profile_section": "Profil",
            "language_section": "Til",
            "appearance_section": "Ko‘rinish",
            "field_first_name": "Ism",
            "field_last_name": "Familiya",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Ilova tili",
            "theme_label": "Mavzu",
            "appearance_system": "iPhone kabi",
            "appearance_light": "Yorug‘",
            "appearance_dark": "Qorong‘i",
            "language_russian": "Ruscha",
            "language_english": "Inglizcha",
            "language_uzbek": "O‘zbekcha",
            "language_uzbek_cyr": "O‘zbekcha · kirill",
            "home_hero_kicker": "SIZNING UMRANGIZ",
            "home_hero_title": "Sizning Umrangiz.\nSizning yo‘lingiz.",
            "home_hero_body": "Parvoz, turar joy va yordam — katta guruh atrofida emas, aynan safaringiz atrofida jamlanadi.",
            "home_hero_cta": "Umramni yig‘ish",
            "home_hero_badge": "Yakuniy narx bron qilishdan oldin ko‘rsatiladi",
            "hotels_title": "Aiomra Hotel Space",
            "hotels_subtitle": "Aiomra jamoasi tomonidan ziyoratchilar uchun tanlangan mehmonxonalar: ishonchli xizmat, qulay joylashuv va xotirjam yashash uchun.",
            "hotels_note": "Aiomra bu mehmonxonalarga egalik qilmaydi. Biz ziyoratchilarimizga mos joylarni sinchiklab tanlaymiz va kuzatib boramiz.",
            "hotels_makkah": "Makka uchun tanlov",
            "hotels_madinah": "Madina uchun tanlov",
            "hotels_selected_badge": "Aiomra tanlovi",
            "hotels_load_error": "Hozir mehmonxonalarni yuklab bo‘lmadi.",
            "booking_hero_kicker": "YANGI SAFAR",
            "booking_hero_title": "Umrangizni yig‘ing",
            "booking_hero_body": "Sanalar, odamlar va safar darajasini tanlang. So‘ng Aiomra mehmonxona tavsiya qiladi va aniq paket narxi bilan mos parvozlarni topadi.",
            "booking_hero_cta": "Umramni yaratish",
            "booking_empty_title": "Hozircha bron yo‘q",
            "booking_empty_body": "Tasdiqlangandan so‘ng birinchi safaringiz shu yerda ko‘rinadi.",
            "trip_intro_kicker": "UMRANGIZNI YIG‘ING",
            "trip_intro_title": "Safaringizdan boshlaymiz",
            "trip_intro_body": "Yo‘nalish, sanalar va yo‘lovchilarni tanlang. Aiomra shu ma’lumotlar asosida mehmonxona va mos parvozlarni topadi.",
            "step_trip": "Safar",
            "step_hotel": "Mehmonxona",
            "step_flight": "Parvoz",
            "step_ready": "Tayyor",
            "trip_continue_hotel": "Mehmonxonaga o‘tish",
            "checkout_title": "Safaringizni tekshiramiz",
            "checkout_subtitle": "Tasdiqlashdan oldin Aiomra tanlangan mehmonxona va parvozlar mavjudligini yana bir bor tekshiradi.",
            "next_title": "Keyin nima bo‘ladi",
            "next_one": "Safarga himoyalangan bron raqami beriladi",
            "next_two": "Mavjudlik tekshiruvi boshlanadi",
            "next_three": "Holat Bron bo‘limida paydo bo‘ladi",
            "next_four": "Aiomra Care chati shu safarga ulanadi",
            "checkout_cta": "Tekshirish va bron yaratish",
            "success_title": "Safar yaratildi",
            "success_body": "Hozir Aiomra mavjudlikni tekshirmoqda. Safar holati va yordam chati shu safarga bog‘landi.",
            "open_booking": "Bronni ochish",
            "open_care": "Aiomra Care'ni ochish",
            "profile_required_title": "Ziyoratchi ma’lumotlari",
            "profile_required_body": "Bron qilishdan oldin ism, familiya va kamida bitta kontaktni kiriting, shunda yordam jamoasi ziyoratchini taniydi.",
            "save_continue": "Saqlash va davom etish",
            "care_title": "Aiomra Care",
            "care_subtitle": "Yordam Umradan oldin, davomida va keyin safaringiz bilan qoladi.",
            "care_chats": "Chatlaringiz",
            "care_chats_subtitle": "Har bir chat aniq safarga bog‘langan, shuning uchun yo‘nalish, sanalar va mehmonxonani qayta tushuntirish shart emas.",
            "care_locked_title": "Chat bron yaratilgach ochiladi",
            "care_locked_body": "Safaringizni yig‘ing va mavjudlikka yuboring. Shundan keyin yordam jamoasi broningizga ulanadi.",
            "care_promise_title": "Mustaqil — yolg‘iz degani emas.",
            "care_promise_body": "Safargacha, yo‘lda va Umra davomida Aiomra Care safaringizga bog‘langan yagona yordam liniyasi bo‘lib qoladi.",
            "chat_online": "online",
            "chat_unavailable": "Chat mavjud emas",
            "chat_empty_title": "Suhbatni boshlang",
            "chat_empty_body": "Bron, parvoz, mehmonxona, transfer yoki yo‘nalish bo‘yicha yozing.",
            "chat_placeholder": "Xabar…",
            "chat_load": "Chat yuklanmoqda…",
            "chat_retry": "Qayta urinish",
            "chat_you": "Siz",
            "chat_staff": "Aiomra Care",
            "status_availability": "Mavjudlik tekshirilmoqda",
            "status_payment": "To‘lov kutilmoqda",
            "status_confirmed": "Bron tasdiqlandi",
            "status_ready": "Safarga tayyor",
            "status_completed": "Safar yakunlandi",
            "detail_booking": "Bron",
            "detail_updates": "Holat avtomatik yangilanadi",
            "detail_chat_cta": "Aiomra Care bilan chat",
            "detail_not_found": "Bron topilmadi",
            "route_label": "Yo‘nalish",
            "route_return": "Qaytish",
            "total_for": "Jami",
            "travelers": "yo‘lovchi uchun"
        ],
        "uz-cyrl": [
            "tab_home": "Асосий",
            "tab_hotels": "Отеллар",
            "tab_booking": "Брон",
            "tab_care": "Care",
            "tab_umrah": "Умра",
            "profile_placeholder": "Профилингиз",
            "profile_subtitle_empty": "Исм ва контактларни қўшинг",
            "profile_subtitle_ready": "Зиёратчи профили",
            "settings_title": "Созламалар",
            "settings_done": "Тайёр",
            "profile_section": "Профиль",
            "language_section": "Тил",
            "appearance_section": "Кўриниш",
            "field_first_name": "Исм",
            "field_last_name": "Фамилия",
            "field_telegram": "Telegram",
            "field_whatsapp": "WhatsApp",
            "app_language": "Илова тили",
            "theme_label": "Мавзу",
            "appearance_system": "iPhone каби",
            "appearance_light": "Ёруғ",
            "appearance_dark": "Қоронғи",
            "language_russian": "Русча",
            "language_english": "Инглизча",
            "language_uzbek": "Ўзбекча",
            "language_uzbek_cyr": "Ўзбекча · кирилл",
            "home_hero_kicker": "СИЗНИНГ УМРАНГИЗ",
            "home_hero_title": "Сизнинг Умрангиз.\nСизнинг йўлингиз.",
            "home_hero_body": "Парвоз, яшаш ва ёрдам — катта гуруҳ атрофида эмас, айнан сафaringиз атрофида жамланади.",
            "home_hero_cta": "Умрамни йиғиш",
            "home_hero_badge": "Якуний нарх брон қилишдан олдин кўрсатилади",
            "hotels_title": "Aiomra Hotel Space",
            "hotels_subtitle": "Aiomra жамоаси томонидан зиёратчилар учун танланган отеллар: ишончли сервис, қулай жойлашув ва хотиржам яшаш учун.",
            "hotels_note": "Aiomra бу отелларга эгалик қилмайди. Биз зиёратчиларимизга мос жойларни синчиклаб танлаймиз ва кузатиб борамиз.",
            "hotels_makkah": "Макка учун танлов",
            "hotels_madinah": "Мадина учун танлов",
            "hotels_selected_badge": "Aiomra танлови",
            "hotels_load_error": "Ҳозир отелларни юклаб бўлмади.",
            "booking_hero_kicker": "ЯНГИ САФАР",
            "booking_hero_title": "Умрангизни йиғинг",
            "booking_hero_body": "Саналар, одамлар ва сафар даражасини танланг. Сўнг Aiomra меҳмонхона тавсия қилади ва аниқ пакет нархи билан мос парвозларни топади.",
            "booking_hero_cta": "Умрамни яратиш",
            "booking_empty_title": "Ҳозирча брон йўқ",
            "booking_empty_body": "Тасдиқлангандан сўнг биринчи сафарингиз шу ерда кўринади.",
            "trip_intro_kicker": "УМРАНГИЗНИ ЙИҒИНГ",
            "trip_intro_title": "Сафaringиздан бошлаймиз",
            "trip_intro_body": "Йўналиш, саналар ва йўловчиларни танланг. Aiomra шу маълумотлар асосида меҳмонхона ва мос парвозларни топади.",
            "step_trip": "Сафар",
            "step_hotel": "Отель",
            "step_flight": "Парвоз",
            "step_ready": "Тайёр",
            "trip_continue_hotel": "Отелга ўтиш",
            "checkout_title": "Сафaringизни текширамиз",
            "checkout_subtitle": "Тасдиқлашдан олдин Aiomra танланган отель ва парвозлар мавжудлигини яна бир бор текширади.",
            "next_title": "Кейин нима бўлади",
            "next_one": "Сафарга ҳимояланган брон рақами берилади",
            "next_two": "Мавжудлик текшируви бошланади",
            "next_three": "Ҳолат Брон бўлимида пайдо бўлади",
            "next_four": "Aiomra Care чати шу сафarga уланади",
            "checkout_cta": "Текшириш ва брон яратиш",
            "success_title": "Сафар яратилди",
            "success_body": "Ҳозир Aiomra мавжудликни текширмоқда. Сафар ҳолати ва ёрдам чати шу сафарга боғланди.",
            "open_booking": "Бронни очиш",
            "open_care": "Aiomra Care'ни очиш",
            "profile_required_title": "Зиёратчи маълумотлари",
            "profile_required_body": "Брон қилишдан олдин исм, фамилия ва камида битта контактни киритинг, шунда ёрдам жамоаси зиёратчини танийди.",
            "save_continue": "Сақлаш ва давом этиш",
            "care_title": "Aiomra Care",
            "care_subtitle": "Ёрдам Умрадан олдин, давомида ва кейин сафaringиз билан қолади.",
            "care_chats": "Чатларингиз",
            "care_chats_subtitle": "Ҳар бир чат аниқ сафарга боғланган, шунинг учун йўналиш, саналар ва отелни қайта тушунтириш шарт эмас.",
            "care_locked_title": "Чат брон яратилгach очилади",
            "care_locked_body": "Сафaringизни йиғинг ва мавжудликка юборинг. Шундан кейин ёрдам жамоаси бронингизга уланади.",
            "care_promise_title": "Мустақил — ёлғиз дегани эмас.",
            "care_promise_body": "Сафаргача, йўлда ва Умра давомида Aiomra Care сафaringизга боғланган ягона ёрдам линияси бўлиб қолади.",
            "chat_online": "онлайн",
            "chat_unavailable": "Чат мавжуд эмас",
            "chat_empty_title": "Суҳбатни бошланг",
            "chat_empty_body": "Брон, парвоз, отель, трансфер ёки йўналиш бўйича ёзинг.",
            "chat_placeholder": "Хабар…",
            "chat_load": "Чат юкланмоқда…",
            "chat_retry": "Қайта уриниш",
            "chat_you": "Сиз",
            "chat_staff": "Aiomra Care",
            "status_availability": "Мавжудлик текширилмоқда",
            "status_payment": "Тўлов кутилмоқда",
            "status_confirmed": "Брон тасдиқланди",
            "status_ready": "Сафарга тайёр",
            "status_completed": "Сафар якунланди",
            "detail_booking": "Брон",
            "detail_updates": "Ҳолат автоматик янгиланади",
            "detail_chat_cta": "Aiomra Care билан чат",
            "detail_not_found": "Брон топилмади",
            "route_label": "Йўналиш",
            "route_return": "Қайтиш",
            "total_for": "Жами",
            "travelers": "йўловчи учун"
        ]
    ]
}
